### ISSUE TITLE
The CSI plugin consumes a lot of disk

### ISSUE THREAD

**Issue by qixiaobo** [kubernetes-sigs/alibaba-cloud-csi-driver#1012]
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/5d0bcbf36246f30130eeed5f15d48e76165ee757/pkg/disk/nodeserver.go#L1091
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/2881751/2e502262-c0e9-4124-a1d1-54b1bc701636)

In this way, the plugin may consumes lots of disk
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/2881751/200c2bc6-62e1-448e-a831-6ad6a308efb1)

**Comment by qixiaobo** [comment]
This can lead to disk pressure and subsequent eviction.
So what is the purpose of this design?

**Comment by qixiaobo** [comment]
Unfortunately, there was an eviction of our production cluster

**Comment by qixiaobo** [comment]
What I mean is that I generated the PV through the Alibaba Cloud CSI plug-in, and mounted it to the pod through the PVC, and the data disk of our host is mounted /var/lib/container, and I can see that the NAS mount point belongs to /var/lib/kubelet/ So it is clear that /var/lib/container/kubelet also has a copy

**Comment by qixiaobo** [comment]
[root@XXX container]# ncdu --one-file-system .
ncdu: Unknown option '--one-file-system'.
[root@XXX container]# ncdu -v
ncdu 1.15.1

**Comment by qixiaobo** [comment]
> [root@XXX container]# ncdu --one-file-system . ncdu: Unknown option '--one-file-system'. [root@XXX container]# ncdu -v ncdu 1.15.1

I found -x instead

**Comment by qixiaobo** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/2881751/7869357b-c40b-4446-b52c-d6dbe703ed18)
/dev/vdb                                                  146G   82G   57G  60% /var/lib/container

**Comment by huww98** [comment]
/var/lib/container/kubelet is bind mounted to /var/lib/kubelet , so basically every related mount point will appear twice. This is  expected, and they don't consume twice disk space. Please read more at https://man7.org/linux/man-pages/man7/mount_namespaces.7.html and search for "propagation".

**Comment by huww98** [comment]
OK, so you should clean up your logs, and this has nothing to do with CSI.

**Comment by qixiaobo** [comment]
> OK, so you should clean up your logs, and this has nothing to do with CSI.

You are right 
I found that Alibaba Cloud's /etc/fstab is as follows
! [image] (https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/2881751/012b41ef-446b-4bc9-b04b-bda046a5e865)
In other words, /var/lib/container/kubelet/XXX/nas/xxx doesn't actually consume the host's disk
I need extra attention to the logs, thanks for the answer

**Comment by qixiaobo** [comment]
> > OK, so you should clean up your logs, and this has nothing to do with CSI.
> 
> You are right I found that Alibaba Cloud's /etc/fstab is as follows ! [image] (https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/2881751/012b41ef-446b-4bc9-b04b-bda046a5e865) In other words, /var/lib/container/kubelet/XXX/nas/xxx doesn't actually consume the host's disk I need extra attention to the logs, thanks for the answer

In addition, ncdu -x is a very effective instruction that I haven't used it before and learned it Thank you for your time, thank you
