### ISSUE TITLE
Still connecting to unix:///var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock

### ISSUE THREAD

**Issue by liangchen-liangchen** [kubernetes-sigs/alibaba-cloud-csi-driver#1014]
## 参考部署文档:
通过 https://help.aliyun.com/zh/nas/user-guide/mount-a-nas-file-system-on-a-self-managed-kubernetes-cluster?spm=a2c4g.11186623.0.i3#69ab5f7059iu2
方法二：通过CSI插件挂载, apply后, 3个worker节点其中一个worker节点无法正常挂载csi.socket文件到容器. 
## Pod日志如下
I0407 01:26:48.067131   25933 main.go:164] Version: unknown
I0407 01:26:48.067159   25933 main.go:165] Running node-driver-registrar in mode=registration
I0407 01:26:48.067711   25933 main.go:189] Attempting to open a gRPC connection with: "/var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock"
I0407 01:26:48.067737   25933 connection.go:154] Connecting to unix:///var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock
W0407 01:26:58.067798   25933 connection.go:173] Still connecting to unix:///var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock
W0407 01:27:08.068344   25933 connection.go:173] Still connecting to unix:///var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock
W0407 01:27:18.068205   25933 connection.go:173] Still connecting to unix:///var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/csi.sock

## worker节点操作系统
cat /etc/redhat-release 
Alibaba Cloud Linux (Aliyun Linux) release 2.1903 LTS (Hunting Beagle)

**Comment by huww98** [comment]
请展示pod中csi-plugin这个容器的日志。

**Comment by liangchen-liangchen** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/d3d66a61-328b-49de-a871-7aa4bd32f756)
有问题的Pod内csi-plugin这个容器没有日志输出, 正常节点上的Pod内csi-plugin容器日志正常, 以下是正常Pod的csi-plugin日志
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/8284d084-91ce-4728-a7d3-5bda38a41d19)

**Comment by huww98** [comment]
可以使用kubectl logs -p查看crash前的日志。

**Comment by liangchen-liangchen** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/4a382392-9158-42d2-ab83-16b0e0b5aa35)

**Comment by liangchen-liangchen** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/5c51ffa8-2587-40ed-a9ee-05840f4e60a1)

**Comment by liangchen-liangchen** [comment]
查看上一个容器退出的日志没有输出

**Comment by huww98** [comment]
没有日志的话，我也无能为力。请自行诊断那个容器为何crash。

**Comment by liangchen-liangchen** [comment]
![1713147466860](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/80ae428e-b1d9-4ac9-a619-7c277fddbd02)

只有describe的信息
Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/eaf63113-577d-44c5-ba7a-549c0dea7ba4/containers/csi-plugin/99b7434b" to rootfs at "/dev/termination-log": open /run/containerd/io.containerd.runtime.v2.task/k8s.io/84db2a59513ac2380a1fb0d416ec6198ba6befef617249328fc8fb534968b616/rootfs/dev/termination-log: read-only file system: unknown


![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/c731e7b5-3afc-48c3-881a-cf871af43fd6)

**Comment by huww98** [comment]
请去除如下yaml片段中的`readonly: true`
```yaml
            - name: host-dev
              mountPath: /dev
              mountPropagation: "HostToContainer"
              readOnly: true
```
我们将会联系NAS团队改进文档。

**Comment by liangchen-liangchen** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/53c921c4-9d7a-4050-8398-ff341b7d1235)
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/55042956/734bd815-71f2-485b-94bc-cfebd67273fa)
解决了, 感谢

**Comment by huww98** [comment]
如果您未来需要使用云盘相关功能的话，dev挂载点还是需要的。

**Comment by liangchen-liangchen** [comment]
暂时不需要云盘, 只需要nas和OSS的挂载, 等help.aliyun.com更新文档我在重新应用下
