### ISSUE TITLE
Does csi plugin support get metadata from Metadata Service in Security hardening mode

### ISSUE THREAD

**Issue by huntkalio** [kubernetes-sigs/alibaba-cloud-csi-driver#1124]
My aliyun Ecs instance turn on Security hardening mode for Metadata Service 。

* https://help.aliyun.com/zh/ecs/user-guide/view-instance-metadata
* https://www.alibabacloud.com/help/en/ecs/user-guide/view-instance-metadata#eaf2293113ad3

I want to know whether the csi plugin can support this feature？

**Comment by huntkalio** [comment]
@huww98  Will this be supported in the future? What time or version will it be?

**Comment by huww98** [comment]
Yes, support will be added.

CSI also pull metadata from other sources (env, k8s node resource, ECS openapi). So CSI may still work for you even if metadata server is not available.
