### ISSUE TITLE
如何挂载已有的云盘

### ISSUE THREAD

**Issue by HuPonya** [kubernetes-sigs/alibaba-cloud-csi-driver#124]
Hello，
请问如何挂载已有的云盘呢？像指定云盘volumeId？我查看了现在的文档和example没有看到有提到相关的信息。

**Comment by fredkan** [comment]
Refer: https://help.aliyun.com/document_detail/127601.html?spm=a2c4g.11174283.6.726.1aad2ceeXkXwgv

We will add the example recently. Thanks.

**Comment by HuPonya** [comment]
Ok, Thank you.
