### ISSUE TITLE
support nodeAffinity in dynamic lvm volume

### ISSUE THREAD

**Issue by fredkan** [kubernetes-sigs/alibaba-cloud-csi-driver#128]
csi-lvm-plugin should support nodeAffinity in dynamic volume.

Currently, the dynamic pv not contains nodeAffinity info, which is useful for some usecases, and must use nodeSelector to schedule Pod to one node.

**Comment by aland-zhang** [comment]
Can refer to the function of Caicloud(才云 ) solution design https://www.infoq.cn/article/kuxs6LbGMR3f7ph*bGpx?utm_source=related_read&utm_medium=article

**Comment by fredkan** [comment]
> Can refer to the function of Caicloud(才云 ) solution design https://www.infoq.cn/article/kuxs6LbGMR3f7ph*bGpx?utm_source=related_read&utm_medium=article

Thanks, The upgraded version add nodeAffinity configuration.
We will continue to improve the implementation.

**Comment by aland-zhang** [comment]
I have tested this nodeAffinity function and I have no problem.

**Comment by fredkan** [comment]
Thanks.
