### ISSUE TITLE
【oss】如果主机上运行的ossfs进程异常退出（比如主机重启，人为误杀），读取数据会有问题。异常，这种

### ISSUE THREAD

**Issue by GitHubxsy** [kubernetes-sigs/alibaba-cloud-csi-driver#154]
这种问题，要如何解决？

**Comment by fredkan** [comment]
主机重启，ossfs会重新被拉起的，pod也会重启，并重新挂载；

如果主机不重启，而是ossfs被误杀，ossfs也会重新被拉起，但是这时pod里面的挂载目录是不可用的。
避免这种情况你可以在pod中定义健康检查，如果发现挂载的oss目录不可用的时候，重启pod。

**Comment by GitHubxsy** [comment]
> 主机重启，ossfs会重新被拉起的，pod也会重启，并重新挂载；
> 
> 如果主机不重启，而是ossfs被误杀，ossfs也会重新被拉起，但是这时pod里面的挂载目录是不可用的。
> 避免这种情况你可以在pod中定义健康检查，如果发现挂载的oss目录不可用的时候，重启pod。

健康检查失败只会重启container，不会触发mount操作。只有是新pod才会触发mount操作。
