### ISSUE TITLE
部署非阿里云机器报错

### ISSUE THREAD

**Issue by guleng** [kubernetes-sigs/alibaba-cloud-csi-driver#155]
`time="2019-12-09T08:07:58Z" level=info msg="CSI Driver Name: nasplugin.csi.alibabacloud.com, , unix://var/lib/kubelet/plugins/nasplugin.csi.alibabacloud.com/csi.sock"
time="2019-12-09T08:07:58Z" level=info msg="CSI Driver Branch: 'v1.0.0', Version: 'v1.14.6-c770df3', Build time: '2019-10-21-11:11:27'\n"
time="2019-12-09T08:07:58Z" level=info msg="Driver: nasplugin.csi.alibabacloud.com version: 1.0.0"
time="2019-12-09T08:08:28Z" level=info msg="Use node id : "
E1209 08:08:28.537891    9811 driver.go:46] NodeID missing
I1209 08:08:28.537904    9811 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x823877]

goroutine 1 [running]:
github.com/kubernetes-sigs/alibaba-cloud-csi-driver/vendor/github.com/kubernetes-csi/drivers/pkg/csi-common.(*CSIDriver).AddVolumeCapabilityAccessModes(0x0, 0xc000281da4, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/driver.go:96 +0x1b7
github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/nas.NewDriver(0x0, 0x0, 0x7ffc7968eb33, 0x46, 0x3)
        /home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/nas/nas.go:59 +0x193
main.main()
        /home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:82 +0x7e1`

**Comment by GitHubxsy** [comment]
NodeID missing。

**Comment by fredkan** [comment]
非阿里云机器需要在模板中添加nodeId配置。

**Comment by guleng** [comment]
@fredkan 是哪个模板中添加nodeID呢？   没太明白

**Comment by fredkan** [comment]
不确定你用的是哪个版本：
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/nas/nas-plugin.yaml
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/nas/nas-provisioner.yaml
这些启动脚本的args里面需要配置。

**Comment by dylanyht** [comment]
我也遇到了这个问题，你们最终是怎么解决的

**Comment by guleng** [comment]
我这个因为是部署在腾讯云，接口不同导致的，在阿里云机器不影响

**Comment by dylanyht** [comment]
@fredkan 您好 你说的nodeid是具体怎么配置  那两个链接已失效
