### ISSUE TITLE
请问registry.cn-hangzhou.aliyuncs.com/acs/csi-provisioner:v1.2.2是否开源，源码存在哪个仓库

### ISSUE THREAD

**Issue by min-qtl** [kubernetes-sigs/alibaba-cloud-csi-driver#175]
请问registry.cn-hangzhou.aliyuncs.com/acs/csi-provisioner:v1.2.2是否开源，源码存在哪个仓库

**Comment by haoshuwei** [comment]
It is just built from this project

**Comment by fredkan** [comment]
https://github.com/kubernetes-csi/external-provisioner
