### ISSUE TITLE
如何部署高可用的 alicloud csi plugin?

### ISSUE THREAD

**Issue by GLYASAI** [kubernetes-sigs/alibaba-cloud-csi-driver#204]
在测试的时候, 我已经部署出了云盘和 nas 的 csi 插件.  但是现在我想用到生产了, 想部署出高可用的 csi 插件, 但是遇到了几个问题:

- 有没有高可用的部署文档?
- csi-plugin 是用 daemonset 跑的, 运行在所有节点,  不需要额外的配置.而 provisioner 是用 statefuleset 跑的,  存储用了 `emptyDir`,  对于这个有状态的服务, 高可用是怎么做的呢? 还是不需要考虑 `emptyDir` 里的内容, 直接运行多个副本就行了.

希望可以解决下我的疑问, 谢谢.

**Comment by fredkan** [comment]
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/ack/csi-provisioner.yaml
