### ISSUE TITLE
存在的磁盘的size和请求磁盘的大小不一致

### ISSUE THREAD

**Issue by zhanlinfeng** [kubernetes-sigs/alibaba-cloud-csi-driver#207]
这个错误什么导致的呢？下面是provisioner错误日志：
I0317 07:32:30.273369       1 utils.go:97] GRPC call: /csi.v1.Controller/CreateVolume
I0317 07:32:30.274084       1 utils.go:98] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.diskplugin.csi.alibabacloud.com/zone":"cn-shenzhen-e"}},{"segments":{"topology.diskplugin.csi.alibabacloud.com/zone":"cn-shenzhen-c"}}],"requisite":[{"segments":{"topology.diskplugin.csi.alibabacloud.com/zone":"cn-shenzhen-c"}},{"segments":{"topology.diskplugin.csi.alibabacloud.com/zone":"cn-shenzhen-e"}}]},"capacity_range":{"required_bytes":21474836480},"name":"pv-disk-5214f4cf-4d6a-492e-a3da-114651bfdc97","parameters":{"fsType":"ext4","regionId":"cn-shenzhen","type":"cloud_ssd","zoneId":"cn-shenzhen-a"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
I0317 07:32:32.600952       1 utils.go:103] GRPC response: {"volume":{"accessible_topology":[{"segments":{"topology.diskplugin.csi.alibabacloud.com/zone":"cn-shenzhen-a"}}],"capacity_bytes":21474836480,"volume_context":{"fsType":"ext4","regionId":"cn-shenzhen","type":"cloud_ssd","zoneId":"cn-shenzhen-a"},"volume_id":"d-wz9d88k7g47jmzhn49sr"}}
time="2020-03-17T07:32:25Z" level=error msg="CreateVolume: exist disk pv-disk-52b1b030-dc36-4de3-853e-8b9e55326d91 size is different with requested for disk: existing size: 20, request size: 20"

**Comment by fredkan** [comment]
double check, if disk is already exist.
