### ISSUE TITLE
How to use ram role instead of set akId and akSecret in yaml?

### ISSUE THREAD

**Issue by liuyangc3** [kubernetes-sigs/alibaba-cloud-csi-driver#221]
It is not safe to save these sensitive information in YAML definition.

**Comment by liuyangc3** [comment]
@fredkan  any thoughts?

**Comment by fredkan** [comment]
oss volume supports ramrole in the volumes.

**Comment by fredkan** [comment]
add "authType": "sts" in pv spec

**Comment by liuyangc3** [comment]
thanks

**Comment by liuyangc3** [comment]
Hi @fredkan ,  another question does the ram role need to attach to the k8s node ECS instance before?
