### ISSUE TITLE
nasplugin.csi.alibabacloud.com/csi.sock: bind: no such file or directory

### ISSUE THREAD

**Issue by jiangxianliang007** [kubernetes-sigs/alibaba-cloud-csi-driver#235]
你好，请教下，我使用 [nas-plugin.yaml](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/nas/nas-plugin.yaml)  插件，新增的node 节点， 宿主机上 /var/lib/kubelet/plugins/nasplugin.csi.alibabacloud.com/ 目录下 没有 生成 csi.sock ，容器启动失败。

![image](https://user-images.githubusercontent.com/24754263/80195949-35b7d580-864f-11ea-96d3-932d80a68cd4.png)

**Comment by fredkan** [comment]
maybe you should use /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com in your deploy yaml file.

**Comment by jiangxianliang007** [comment]
谢谢，我使用了ack  已经正常。
