### ISSUE TITLE
k8s 1.14 安装插件pod报错

### ISSUE THREAD

**Issue by lakers-jiangxp** [kubernetes-sigs/alibaba-cloud-csi-driver#248]
Error from server (BadRequest): a container name must be specified for pod csi-provisioner-69b6844d94-mqhlt, choose one of: [external-disk-provisioner external-disk-attacher external-disk-resizer csi-diskprovisioner dusk-liveness-probe external-nas-provisioner csi-nasprovisioner nas-liveness-probe]

Error from server (BadRequest): a container name must be specified for pod csi-plugin-7n2w8, choose one of: [disk-driver-registrar csi-diskplugin disk-liveness-probe nas-driver-registrar csi-nasplugin nas-liveness-probe oss-driver-registrar csi-ossplugin oss-liveness-probe]

**Comment by fredkan** [comment]
这个错误是看日志的报错吧？需要加上-c containerName

**Comment by lakers-jiangxp** [comment]
这个错误是看日志的报错吧？需要加上-c containerName； 在哪儿加配置，在插件的yaml文件中吗

**Comment by fredkan** [comment]
reopen this if issue exist
