### ISSUE TITLE
如何在Nomad下部署alibaba-cloud-csi plugins

### ISSUE THREAD

**Issue by mandarenmanman** [kubernetes-sigs/alibaba-cloud-csi-driver#256]
https://github.com/container-storage-interface/spec

Container Orchestrators (CO)
Cloud Foundry
Kubernetes
Mesos
Nomad

https://www.nomadproject.io/docs/internals/plugins/csi/

**Comment by fredkan** [comment]
插件没有在Nomad 环境适配过，如有需求可以用代码调试一下，并一起交流。
