### ISSUE TITLE
 创建pv失败

### ISSUE THREAD

**Issue by guleng** [kubernetes-sigs/alibaba-cloud-csi-driver#260]
1. k8s version : v1.14.1

2. 部署的是csi-driver文档里的最新版本，挂载的是阿里云的NAS服务

3. 部署版本：
    csi-provisioner:
        csi-nasplugin:v1.14.6-c770df3
        csi-provisioner:v1.2.0
    nas-plugin:
        nas-plugin:csi-nasplugin:v1.14.6-c770df3
        csi-node-driver-registrar:v1.1.0

4. 之前用StorageClass后创建pv是没问题正常的，但现在是我再使用之前的StorageClass时报
![image](https://user-images.githubusercontent.com/40238640/86335342-f75b1a00-bc80-11ea-863f-a28e1a93bd22.png)
或者我再使用之前的nas实例分目录方式创建StorageClass后挂载时都同样结果，pvc是Pending状态，无法创建pv。
我是ubuntu系统，nfs-common是装好的。
![image](https://user-images.githubusercontent.com/40238640/86336515-887ec080-bc82-11ea-98dc-3ce097719b77.png)

我新申请NAS后创建StorageClass挂载是正常的。

**问题：**
1.同一个nas实例用csi-driver去连接时候有连接数上限么？

**Comment by fredkan** [comment]
收到问题，这个issue应该是provision失败，但是异常卸载的问题，我们复现一下。

**Comment by fredkan** [comment]
fixed
