### ISSUE TITLE
Does it support EBS block storage  type PV expanding or resize ?

### ISSUE THREAD

**Issue by zengyongjie** [kubernetes-sigs/alibaba-cloud-csi-driver#261]
I used the plugin to provision alibaba ebs disk as kubernetes  storage , I tryed to resize a pvc provisioned before, but it seems doesnot support expand.

``` log
didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

my k8s version is 1.18.2

**Comment by fredkan** [comment]
In 1.16 cluster, the plugin works. 1.18 should also be OK. 
pls provider the detail logs.
