### ISSUE TITLE
Private mount flag will block other pod's termination

### ISSUE THREAD

**Issue by lxs137** [kubernetes-sigs/alibaba-cloud-csi-driver#267]
### 描述

部署有这个 csi 插件的宿主机，宿主机上的所有其他容器都无法被正常删除，会阻塞在 Terminating 状态

P.S. 并不是所有的 Linux 发行版都可以复现这个 bug，在 `Alibaba Group Enterprise Linux Server 7.2`上可以复现，在 `CentOS Linux 7` 上不能复现，**原因未知**

### 原因
* VolumeMount 默认的 MountPropagation 是 None，也就是 private mount，这意味着宿主机 mountpoint 的 umount 事件不会传播到容器中。所以如果将 `/var/lib/kubelet` 挂载到某个`容器-A`中，意味着在`容器-A`中可以看到这个宿主机上所有容器被挂载。
* 当某个`容器-B`被删除时，kubelet 会尝试去umount `容器-B` 下的`Volume-BV`，但`Volume-BV`的 umount 事件无法被传播到`容器-A`中，所以在`容器-A`中仍然可以看到`Volume-BV`被挂载。此时，宿主机的 kubelet 在尝试删除`Volume-BV`的挂载点对应的目录时，kernel 发现在某个 mount namespace 中这个目录仍然被挂载（`容器-A`的 mount namespace），会报错"device or resource busy"，`Volume-BV`无法被 umount，导致`容器-B`无法被删除，一直处于 Terminating 状态。
* 其中，这个`容器-A`对应与 csi-plugin 中的 driver-registrar 容器，对应存在问题的 pod 配置如下（不止这几处）：

https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/6ce04cfd626f74ca182ef1ebfac6502694a08d68/deploy/ack/csi-plugin.yaml#L53-L55

https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/6ce04cfd626f74ca182ef1ebfac6502694a08d68/deploy/agent/csi-plugin.yaml#L53-L55

**Comment by fredkan** [comment]
MountPropagation 配置为Bidirectional 是否可以呢？

**Comment by fredkan** [comment]
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/6ce04cfd626f74ca182ef1ebfac6502694a08d68/deploy/ack/csi-plugin.yaml#L97

**Comment by fredkan** [comment]
reopen this if issue happens
