### ISSUE TITLE
在ASK上安装nas-provisioner失败

### ISSUE THREAD

**Issue by einsone** [kubernetes-sigs/alibaba-cloud-csi-driver#281]
在ASK上执行`kubectl apply -f deploy/nas/nas-provisioner.yaml`，安装失败

失败事件
SDK.ServerError ErrorCode: InvalidParameter Recommend: RequestId: XXXXX Message: The specified parameter HostPathVolume is not valid.

**Comment by fredkan** [comment]
ask is not supported
