### ISSUE TITLE
选举失败导致重启

### ISSUE THREAD

**Issue by sunnoy** [kubernetes-sigs/alibaba-cloud-csi-driver#284]
![image](https://user-images.githubusercontent.com/19342276/89766472-c943e200-db2a-11ea-9cde-68ee4ae1e725.png)

**Comment by fredkan** [comment]
pod所在两个节点的hostname一致吗？

**Comment by sunnoy** [comment]
不一致

**Comment by guleng** [comment]
遇到相同问题：
k8s:1.14.1

![image](https://user-images.githubusercontent.com/40238640/97972960-4c11cb80-1e00-11eb-9847-aab24796e982.png)
![image](https://user-images.githubusercontent.com/40238640/97973027-63e94f80-1e00-11eb-8d40-c20d3ef865bd.png)
我俩个pod日志状态一个一直报successfully另一个报failed，集群状态及网络正常

**Comment by fredkan** [comment]
retry with kuberentes 1.18 release and csi 1.1.0.

**Comment by fredkan** [comment]
reopen this issue if problem reproduce
