### ISSUE TITLE
不运行在阿里机器上的csi-plugin无法执行regionId为optional的相关ecs命令

### ISSUE THREAD

**Issue by EmoinLanyu** [kubernetes-sigs/alibaba-cloud-csi-driver#285]
**背景**：

- 目前 vendor 的 `alibaba-cloud-go-sdk` for ECS service 在新建 `client` 时会默认将 `ecsClient` 的 `EndpointType` 设置为 `regional`，见：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/dd34779ff48624e2fef4563960046bc561a39714/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/ecs/client.go#L40

- 而 client 发送请求时，会先进行检测，`client.regionId` 和 `request.GetRegionId()` 至少有一个不为空，见：https://github.com/aliyun/alibaba-cloud-sdk-go/blob/0bf1164687a6b1a30b521b9b4421386ecf4f14b6/sdk/client.go#L328

- 在 `csi-plugin` 进行 `NewEcsClient` 时，会尝试通过 `GetMetaData("region-id")` 获得 `regionId` 并配置到 `client` 上，见：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/dd34779ff48624e2fef4563960046bc561a39714/pkg/disk/utils.go#L136

- `csi-plugin` 会尝试从 `http://100.100.100.200/latest/meta-data/region-id` 获取 `regionId`

**问题**：

- 当 `csi-plugin` 不运行在阿里的机器上时（比如，它随一个 k8s 机器的 control plane 存在于另一个机器上），它就无法获得正确的 `regionId`

- 这导致 `client.regionId` 和 `request.GetRequestId()` 都为空，从而在如 `AttachDisk`, `DetachDisk`, `DeleteDisk` 时报错：`RegionId is empty, please set a valid RegionId.`

**可能的解决方法**：

- 在 `ecs.CreateXXXRequest()` 之后，手动 `request.RegionId = GlobalConfigVar.RegionId`：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/pkg/disk/controllerserver.go#L336

- 在 `regionId = GetMetaData("region-id")` 时，如果 `GlobalConfigVar.RegionId != ""`，`regionId = GlobalConfigVar.RegionId`：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/dd34779ff48624e2fef4563960046bc561a39714/pkg/disk/utils.go#L136

**Comment by fredkan** [comment]
fixed
