### ISSUE TITLE
Port conflict when start csi-provisioner & csi-plugin in kubernetes cluster

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-sigs/alibaba-cloud-csi-driver#294]
```csi-plugin-contianer-merge.yaml``` & ```csi-provisioner-container-merge.yaml``` can started successfully, but ```csi-plugin.yaml``` & ```csi-provisioner.yaml``` are not, seems like should renew the yaml files for new code?

**Comment by fredkan** [comment]
yes, csi 1.1.0 will released with new template
