### ISSUE TITLE
upgrade guide for CSI version after v1.14.8.36

### ISSUE THREAD

**Issue by abowloflrf** [kubernetes-sigs/alibaba-cloud-csi-driver#303]
Hi, I want to upgrade my CSI plugin for my ACK cluster cuz I met this problem #277.  However, there seems have no detail for the version after `v1.14.8.36` as the  [offical guide](https://developer.aliyun.com/article/745944) illustrated. I wonder if it would be ok if I just update the image version for `csi-plugin` and `csi-provisioner`.

![image](https://user-images.githubusercontent.com/17028350/94220248-2a791680-ff1b-11ea-80a6-99f3138d28e2.png)

![image](https://user-images.githubusercontent.com/17028350/94220708-2ef1ff00-ff1c-11ea-9138-50b20f1978aa.png)

**Comment by fredkan** [comment]
updated
