### ISSUE TITLE
使用 阿里高效云盘 无法动态扩容

### ISSUE THREAD

**Issue by hyt05** [kubernetes-sigs/alibaba-cloud-csi-driver#316]
kubernetes版本：v1.18.3
操作系统：Centos7.8
内核：3.10

##使用  kubectl logs -f -n kube-system csi-resizer-0 csi-resizer  查看容器出现如下报错
E1020 01:40:27.542874       1 leaderelection.go:306] error retrieving resource lock kube-system/external-resizer-diskplugin-csi-alibabacloud-com: leases.coordination.k8s.io "external-resizer-diskplugin-csi-alibabacloud-com" is forbidden: User "system:serviceaccount:kube-system:admin" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
I1020 01:40:27.542916       1 leaderelection.go:222] failed to acquire lease kube-system/external-resizer-diskplugin-csi-alibabacloud-com
E1020 01:40:36.173704       1 leaderelection.go:306] error retrieving resource lock kube-system/external-resizer-diskplugin-csi-alibabacloud-com: leases.coordination.k8s.io "external-resizer-diskplugin-csi-alibabacloud-com" is forbidden: User "system:serviceaccount:kube-system:admin" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
I1020 01:40:36.173729       1 leaderelection.go:222] failed to acquire lease kube-system/external-resizer-diskplugin-csi-alibabacloud-com
E1020 01:40:46.820167       1 leaderelection.go:306] error retrieving resource lock kube-system/external-resizer-diskplugin-csi-alibabacloud-com: leases.coordination.k8s.io "external-resizer-diskplugin-csi-alibabacloud-com" is forbidden: User "system:serviceaccount:kube-system:admin" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"

部署时使用的rbac配置清单为https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/rbac.yaml 

中缺少了"coordination.k8s.io"  api 组的授权，
我新加该资源组，错误消失了
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "list", "watch", "delete", "update"]

在执行 kubectl edit pvc html-nginx-csi-0 修改spec.resources.requests.storage 调大后出现新的权限失败

cannot patch resource "persistentvolumeclaims/status" in API group "" in the namespace "default"

接下来我又新加rbac权限
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["get", "list", "watch", "patch"]

再次执行 kubectl edit pvc html-nginx-csi-0 修改spec.resources.requests.storage 新的错误
update capacity of PV d-wz91em5z35519lul3fgk failed: persistentvolumes "d-wz91em5z35519lul3fgk" is forbidden: User "system:serviceaccount:kube-system:admin" cannot patch resource "persistentvolumes" in API group "" at the cluster scope

依然缺少权限
修改前
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
修改后
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]

执行 kubectl  apply -f   rbac.yaml

动态扩容成功

**Comment by hyt05** [comment]
是否可以更新rbac清单文件至仓库，避免更多人踩坑
##完整的rbac权限，
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alicloud-csi-plugin
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "list", "watch", "delete", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alicloud-csi-plugin
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: alicloud-csi-plugin
  apiGroup: rbac.authorization.k8s.io

**Comment by fredkan** [comment]
收到，谢谢。
