### ISSUE TITLE
Describe node  with error: resource name may not be empty

### ISSUE THREAD

**Issue by guleng** [kubernetes-sigs/alibaba-cloud-csi-driver#325]
我部署完有这样的error
![image](https://user-images.githubusercontent.com/40238640/98087361-e9313a80-1eba-11eb-845f-db70173d5758.png)

k8s版本:1.14.1
csi-driver版本：master分支最新版本
部署环境：阿里云ecs，非ack环境，自建k8s

报以上错误，是我哪里有配置错误么？
但是创建pv看起来没什么问题。
谢谢！

**Comment by shenshouer** [comment]
@guleng 你这个问题怎么解决的，我现在也碰到一样的报错了
