### ISSUE TITLE
allowVolumeExpansion 不生效

### ISSUE THREAD

**Issue by kong62** [kubernetes-sigs/alibaba-cloud-csi-driver#33]
# cat storageclass_hdd.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: alicloud-csi-disk-efficiency 
   annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    zoneId: cn-hangzhou-g
    regionId: cn-hangzhou
    fsType: ext4
    type: cloud_efficiency
    readOnly: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true

# cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc-efficiency
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-csi-disk-efficiency

# kubectl get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                   AGE
disk-pvc-efficiency   Bound    pvc-d53ed818-8840-11e9-a463-00163e116758   20Gi       RWO            alicloud-csi-disk-efficiency   21m

当我将 pvc 改成 30 GI 时候，没有发现扩容：
# cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc-efficiency
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: alicloud-csi-disk-efficiency

# kubectl get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                   AGE
disk-pvc-efficiency   Bound    pvc-d53ed818-8840-11e9-a463-00163e116758   20Gi       RWO            alicloud-csi-disk-efficiency   21m

**Comment by kong62** [comment]
谁可以帮忙解决下，目前 ElasticSearch 的存储爆掉了，急需扩容

**Comment by fredkan** [comment]
@kong62 停掉应用，然后扩容云盘，然后再重新挂载；
参考：https://yq.aliyun.com/articles/629008?spm=a2c4e.11155435.0.0.1d23e11awJPgtw

**Comment by fredkan** [comment]
allowVolumeExpansion 还不支持

**Comment by kong62** [comment]
@fredkan 
谢谢你提供的思路。不过这边还有问题：
1， pvc、pv 上显示的还是扩容前的，后期难于维护
2，手工做这些操作繁琐也容易出错

**Comment by fredkan** [comment]
@kong62 是的，从应用角度非常需要一个在线扩容的功能，这个feature还在筹划中。
社区目前也有项目在跟进。https://github.com/kubernetes-csi/external-resizer

不过在线扩容也需要底层存储的支持，例如lvm、rbd之类的存储可以容易实现在线扩容，但很多存储类型目前尚不支持。

**Comment by cuericlee** [comment]
can we support expand block storage firstly, then consider to resize fs from application layer. the similar case for ssd snapshot support!

**Comment by fredkan** [comment]
Feature Supported: 
https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/disk-resizer.md
