### ISSUE TITLE
我在阿里云的ECS主机上自建了Kubernetes集群，想使用阿里云的块存储作为k8s容器集群的后端存储，我应该使用下面的哪一个配置呢？

### ISSUE THREAD

**Issue by zengyongjie** [kubernetes-sigs/alibaba-cloud-csi-driver#331]
![image](https://user-images.githubusercontent.com/62204644/99208015-5b2e4b80-27fa-11eb-82ef-39920bed5065.png)

应该用managed还是dedicated配置？

**Comment by fredkan** [comment]
用dedicate配置；

**Comment by felix-hxz** [comment]
@zengyongjie成功了嘛

**Comment by zengyongjie** [comment]
> @zengyongjie成功了嘛

成功了

**Comment by fredkan** [comment]
thanks
