### ISSUE TITLE
文档上是否再可以详细一点啊？

### ISSUE THREAD

**Issue by zengyongjie** [kubernetes-sigs/alibaba-cloud-csi-driver#332]
譬如我要使用云盘作为后端存储，但是就不知道该使用哪一个配置文件？文档能在详细一点吗？

还有deploy 下面能否给出使用该种类型的后后端存储所需要的所有yaml文件呢？  不要这里找一个，哪里找一个？ 

例如disk-plugin.yaml里面使用了一个serviceaccount，但是没有创建这个service-account的yaml文件，需要来回反复查找。

**Comment by fredkan** [comment]
thanks.
