### ISSUE TITLE
nas连接检查超时设置过短

### ISSUE THREAD

**Issue by hongyuan1306** [kubernetes-sigs/alibaba-cloud-csi-driver#356]
根据`deploy/nas/nas-plugin-dedicated`的配置设置nas静态卷后，发现pod创建时无法加载nas卷，日志显示如下：

```
E1128 00:50:41.372565  394803 utils.go:101] GRPC error: NAS: Cannot connect to nas host: 009bb4952f-qik20.cn-hangzhou.nas.aliyuncs.com
```

然而从容器中手工运行`mount -t nfs`命令可以加载nas卷。

查看源代码发现在运行`mount`前有个连接检测使用了3s的timeout。

https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/a8df2c8bb06c9fb649457279f5c2023ecf3f7092/pkg/nas/nodeserver.go#L185-L191

怀疑是时间不够，修改源码为15s，重新编译新镜像后，容器可以正常连接nas卷了。

**建议**

将这个3s延长或者作为一个可以在配置文件中修改的配置项

**Comment by fredkan** [comment]
谢谢，可以考虑加个环境变量。
不过3秒都无法连接nas服务端，更需要查看网络问题，否则就是挂载成功了，也会很卡，或者链接出现问题；

**Comment by hongyuan1306** [comment]
@fredkan  你说的对。这个问题更主要的是Kubernetes的网络环境问题，而不是csi代码的问题。

使用阿里云托管版，就没有这个延迟。我估计是我的自建集群CNI插件配置的问题。
