### ISSUE TITLE
ubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name nasplugin.csi.alibabacloud.com not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by Super-DoXCDH** [kubernetes-sigs/alibaba-cloud-csi-driver#395]
[Issues news](https://raw.githubusercontent.com/Super-DoXCDH/learngit/master/images/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20210127105935.png)

**Comment by Super-DoXCDH** [comment]
我刚刚部署成功了，一般是部署文件的问题：https://blog.csdn.net/weixin_44124824/article/details/113516917

**Comment by fredkan** [comment]
新版本解决了一些nas Provision 失败的问题。
