### ISSUE TITLE
Docs NAS dedicated or managed?

### ISSUE THREAD

**Issue by hrvatskibogmars** [kubernetes-sigs/alibaba-cloud-csi-driver#396]
Not sure what to deploy for NAS on version 1.1.0

Now there are 4 yaml files 2 per type dedicated or managed.
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/tree/master/deploy/nas
What we use is NAS subpath, docs didn't get updated, so not sure what to use now.

What I used before was this 
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/nas-dynamic.md
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/tree/release-v1.0.7/deploy/nas
So I deployed  _nas-plugin_ and _nas-provisioner_  and everything worked fine.

Can somebody point me to docs or what should I use?

**Comment by JiaoDean** [comment]
Please use the template in the ack folder to deploy nas. The yaml template in the nas folder is no longer maintained, and we will delete it later.Thanks.

**Comment by hrvatskibogmars** [comment]
Thanks
