### ISSUE TITLE
自建k8s集群中安装nas-csi插件时出错

### ISSUE THREAD

**Issue by dylanyht** [kubernetes-sigs/alibaba-cloud-csi-driver#400]
[root@k8s-77-35 ~]# kubectl logs -n kube-system csi-provisioner-7bc58d984d-f6sgr -c csi-provisioner -f
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0curl: (7) Failed connect to 100.100.100.200:80; Connection timed out
Running nas plugin....
time="2021-01-31T08:43:01Z" level=info msg="Multi CSI Driver Name: nas, nodeID: , endPoints: unix://var/lib/kubelet/csi-provisioner/driverplugin.csi.alibabacloud.com-replace/csi.sock"
time="2021-01-31T08:43:01Z" level=info msg="CSI Driver Branch: 'master', Version: 'v1.16.9.43-f36bb540-aliyun', Build time: '2020-10-12-21:54:17'\n"
time="2021-01-31T08:43:01Z" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/controller"
time="2021-01-31T08:43:01Z" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/node"
time="2021-01-31T08:43:01Z" level=info msg="CSI is running status."
time="2021-01-31T08:43:01Z" level=info msg="Metric listening on address: /healthz"
time="2021-01-31T08:43:01Z" level=info msg="Driver: nasplugin.csi.alibabacloud.com version: 1.0.0"
time="2021-01-31T08:43:31Z" level=info msg="Use node id : "
E0131 08:43:31.295445      11 driver.go:46] NodeID missing
I0131 08:43:31.295452      11 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x16de344]

goroutine 75 [running]:
github.com/kubernetes-csi/drivers/pkg/csi-common.(*CSIDriver).AddVolumeCapabilityAccessModes(0x0, 0xc000113f14, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/regressionTest/go/pkg/mod/github.com/kubernetes-csi/drivers@v1.0.2/pkg/csi-common/driver.go:96 +0x1c4
github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/nas.NewDriver(0x0, 0x0, 0xc000702140, 0x4e, 0x0)
	/home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/nas/nas.go:78 +0x1af
main.main.func1(0xc000136224, 0xc000702140, 0x4e)
	/home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:180 +0x79
created by main.main
	/home/regressionTest/go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:178 +0xfe5

k8s版本为1.18.3

**Comment by Super-DoXCDH** [comment]
我刚刚部署成功了，一般是部署文件的问题：https://blog.csdn.net/weixin_44124824/article/details/113516917

**Comment by dylanyht** [comment]
你这个文档能在私有云中部署吗？我的报错是没有nodeid  我的目前处理好了  但部署文件和你文档中的不一样

**Comment by Super-DoXCDH** [comment]
注意要和主机在同一个阿里专有网，可以跨可用区；

**Comment by Super-DoXCDH** [comment]
你也可以分享一下么，我当时还去把原理走了一边⁽⁽◞(꒪ͦᴗ̵̍꒪ͦ=͟͟͞͞ ꒪ͦᴗ̵̍꒪ͦ)◟⁾⁾

**Comment by dylanyht** [comment]
在最新的文档中的nas-provisioner-dedicated.yaml、nas-plugin-dedicated.yaml文件中的csi-plugin的配置部分都需要加上下图的内容，给plugin传入一个唯一的nodeid，在私有云因为不是阿里云机器不会自动传入。
![image](https://user-images.githubusercontent.com/49978436/106538522-547cbe00-6537-11eb-941f-911f9995b87d.png)
