### ISSUE TITLE
How does ossfs start on the host machine

### ISSUE THREAD

**Issue by boddumanohar** [kubernetes-sigs/alibaba-cloud-csi-driver#411]
I came across [this doc ](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/oss-upgrade.md)as a solution for mounting FUSE filesystem.

But does the customer need to start ossfs on the host machine? are we doing this using containers? or alibaba installs this automatically on its cloud environment?

**Comment by fredkan** [comment]
csi plugin start the ossfs command in host machine.
use csi-connector for the operation.
