### ISSUE TITLE
default-scheduler  0/1 nodes are available: 1 node(s) had volume node affinity conflict.

### ISSUE THREAD

**Issue by felix-hxz** [kubernetes-sigs/alibaba-cloud-csi-driver#415]
ecs单节点 云盘   一直提示这个，卷创建成功了，attach这个csi组件一直没生效 ，事件没触发default-scheduler  0/1 nodes are available: 1 node(s) had volume node affinity conflict.

**Comment by felix-hxz** [comment]
@Kan Junbao可以解答下嘛

**Comment by felix-hxz** [comment]
云盘区域和k8s版本问题，已解决

**Comment by fredkan** [comment]
> 云盘区域和k8s版本问题，已解决

云盘和ecs要在相同可用区的。
👍
