### ISSUE TITLE
How can we change pv in SSD disk type to ESSD disk type

### ISSUE THREAD

**Issue by syy6** [kubernetes-sigs/alibaba-cloud-csi-driver#435]
Hello, we have K8S cluster with pv in SSD disk type on AliCloud, since some new zone like L in cn-shanghai only have ESSD disk now. We hope to migirate all the pv to ESSD, if there is any direct way we can do it? Seems like we can't change the storageclass directly. Thanks!

**Comment by fredkan** [comment]
you can change the disk type in ecs console
