### ISSUE TITLE
Image tags are not semver

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/alibaba-cloud-csi-driver#444]
/sig release
/sig storage

**What would you like to be added/changed**:
Currently the image tags are not semver versions.

```
registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.18.8.45-1c5d2cd1-aliyun
```

The image tag `v1.18.8.45-1c5d2cd1-aliyun` does not match the [semver version regex](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string).

For example the equivalent semver image tag would be `v1.18.8-1c5d2cd1-aliyun`.

```
^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

To my knowledge there is https://github.com/kubernetes/cloud-provider-alibaba-cloud that uses non-semver image tags as well. I opened a similar issue to the https://github.com/kubernetes/cloud-provider-alibaba-cloud repo as well - see https://github.com/kubernetes/cloud-provider-alibaba-cloud/issues/254.

**Why is this needed**:
In CI/CD systems it is common practice to have manipulations over the image tags - for example you need to compare image tags (versions); find an image tag (version) that matches certain constraint; etc.
Currently it is not possible to use a semver library to parse an image tag such as `v1.18.8.45-1c5d2cd1-aliyun`.

**Comment by fredkan** [comment]
image tag will be formatted in next released. thanks.

**Comment by ialidzhikov** [comment]
> image tag will be formatted in next released. thanks.

Thank you 🙇

**Comment by ialidzhikov** [comment]
Hello @fredkan 👋 

When it is expected to have a new release? We are looking forward to try out the semver image tags. :)

**Comment by fredkan** [comment]
have fixed. Thanks.

**Comment by ialidzhikov** [comment]
Image tag `v1.20.5-ff6490f-aliyun` looks much better. Thank you very much!
