### ISSUE TITLE
用官网yaml文件在Kubernetes1.8下挂载失败，但用老版本可以成功。

### ISSUE THREAD

**Issue by lq2015** [kubernetes-sigs/alibaba-cloud-csi-driver#459]
- 报错日志：
```
  addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/ossplugin.csi.alibabacloud.com-reg.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/ossplugin.csi.alibabacloud.com-reg.sock: connect: no such file or directory". Reconnecting...
  
  Operation for "/var/lib/kubelet/plugins_registry/ossplugin.csi.alibabacloud.com-reg.sock" failed. No retries permitted until 2021-06-09 11:06:22.384089299 +0800 CST m=+979.272194638 (durationBeforeRetry 1m4s). Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/ossplugin.csi.alibabacloud.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/ossplugin.csi.alibabacloud.com-reg.sock, err: context deadline exceeded"
```
- 其他现象：
发现/var/lib/kubelet/plugins_registry/ossplugin.csi.alibabacloud.com-reg.sock未创建

- 成功版本信息: 
```
OSSFS版本:ossfs-1.80.6-1.x86_64
driver镜像版本:registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.1.0
csi-plugin镜像版本: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.14.8.32-c77e277b-aliyun
```

**Comment by fredkan** [comment]
你的kubelet的根目录是什么？是ack集群还是自建集群啊？

**Comment by lq2015** [comment]
自建集群




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes-sigs/alibaba-cloud-csi-driver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月7日(星期三) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes-sigs/alibaba-cloud-csi-driver] 用官网yaml文件在Kubernetes1.8下挂载失败，但用老版本可以成功。 (#459)





 
你的kubelet的根目录是什么？是ack集群还是自建集群啊？

**Comment by fredkan** [comment]
此问题像是root dir导致的注册问题，需要提供一些日志说明。
可加入钉钉群交流：33936810
