### ISSUE TITLE
阿里云ECS上自建K8S集群，使用云盘(diskplugin.csi.alibabacloud.com)，无法创建pod

### ISSUE THREAD

**Issue by gucci** [kubernetes-sigs/alibaba-cloud-csi-driver#469]
Warning  FailedScheduling        32m                   default-scheduler        0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               32m                   default-scheduler        Successfully assigned default/deployment-disk-5cbdd9b45c-vpxhs to 10.50.160.4
  Normal   SuccessfulAttachVolume  32m                   attachdetach-controller  AttachVolume.Attach succeeded for volume "d-uf6amg7m43juwo2pkmto"
  Warning  FailedMount             2m50s (x12 over 30m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[disk-pvc], unattached volumes=[disk-pvc kube-api-access-p5k7w]: timed out waiting for the condition
  Warning  FailedMount             35s (x2 over 23m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[disk-pvc], unattached volumes=[kube-api-access-p5k7w disk-pvc]: timed out waiting for the condition

**Comment by fredkan** [comment]
看一下日志/var/log/alicloud/**log

**Comment by fredkan** [comment]
若还有问题，您可以加入钉钉交流群：33936810
