### ISSUE TITLE
几个关于资源的问题确认

### ISSUE THREAD

**Issue by iswbm** [kubernetes-sigs/alibaba-cloud-csi-driver#479]
## 环境

单台Master  三台worker 的 K8S 集群，仅部署了 lvm-plugin.yaml 和 lvm-provisioner.yaml
worker01 上没有 vg，worker02 上有 test_vg

## 问题

**第一个问题**

创建一台 lvm 的虚拟机，在创建 importer 的 Pod 时，是有可能创建到 没有 vg 的 worker01 上去的，此时 impoter 会因为找不到 test_vg 而失败（或者假如 work01 上也有 vg，但 vg 资源不够创建这台虚拟机这样的失败）。

失败后并不会重新走重调度，去选择 worker02 创建。请问这是本身插件还不支持重调度的功能吗？还是已经实现了，只是我使用方法不对呢？

**第二个问题**

当成功创建一台虚拟机后，对虚拟机做删除操作。

对应的 PVC PV 都会删除，但是 worker 节点上的 LV 并不会清理，会一直占用空间，需要手动清理，如果想要做到在虚拟机删除后，自动清理应该如何实现呢？

以上，两个问题期待大佬的解答~

**Comment by fredkan** [comment]
第一个问题：
方案1：可以通过给节点加label，通过nodeselector的方式将pod选定vg节点；
方案2：为lvm添加调度，这个目前没有开源。后续会发布；

第二个问题：
”当成功创建一台虚拟机后，对虚拟机做删除操作。“ 你这里说的虚拟机是Pod吧？
lvm和pv的声明周期是一样的，你要想删除lvm，就需要把pvc/pv删除；

**Comment by iswbm** [comment]
感谢回复。

第一个问题，文案2 请问是 [LVM数据卷](https://help.aliyun.com/document_detail/178476.html) 中的图示的存储调度器组件吗？
![](https://user-images.githubusercontent.com/22311419/125937574-cb940615-ec4c-46d5-9b5f-c294c26a9cc9.png)

第二个问题，指的是删除 vm 或者 vmi 对象，这边验证的结果是 pvc 和 pvc 有删除，但是 worker 节点上的对应的 lv 没有删除。代码中好像只有做 umount 操作，并没有删除 lv的操作。
![](https://user-images.githubusercontent.com/22311419/125938189-6e7259df-c3e1-4344-817f-062acfcaf119.png)

**Comment by comeonbabydontbeshy** [comment]
我也碰到pv删除后，vg还存在的问题，这个有办法自动删除吗

**Comment by huww98** [comment]
> 我也碰到pv删除后，vg还存在的问题，这个有办法自动删除吗

你说的是LVM里的volume group？这个自然是不会删除的，Kubernetes里的PV对应的是LVM的Logical Volume （LV）

**Comment by comeonbabydontbeshy** [comment]
> > 我也碰到pv删除后，vg还存在的问题，这个有办法自动删除吗
> 
> 你说的是LVM里的volume group？这个自然是不会删除的，Kubernetes里的PV对应的是LVM的Logical Volume （LV）

抱歉，是的，LV没有删除，这个有办法自动删除吗

**Comment by huww98** [comment]
按理是会删除的，请查看下Kubernetes的PV上是否有相关event。如果没有，请提供日志，以及组件版本等信息。

对了，触发清理LV是删除PVC，而不是PV。请勿手动删除Kubernetes里的PV。

**Comment by comeonbabydontbeshy** [comment]
> 按理是会删除的，请查看下Kubernetes的PV上是否有相关event。如果没有，请提供日志，以及组件版本等信息。
> 
> 对了，触发清理LV是删除PVC，而不是PV。请勿手动删除Kubernetes里的PV。

组件版本信息：
registry-cn-hangzhou.ack.aliyuncs.com/acs/csi-provisioner:v3.5.0-e7da67e52-aliyun
registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.26.4-e7e52e9-aliyun
registry-cn-hangzhou.ack.aliyuncs.com/acs/csi-node-driver-registrar:v2.3.1-038aeb6-aliyun

日志如下：
I0605 16:43:36.389963    6827 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0605 16:43:36.389981    6827 utils.go:98] GRPC request: {}
I0605 16:43:36.390036    6827 utils.go:103] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":3}}}]}
I0605 16:44:17.128542    6827 utils.go:97] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0605 16:44:17.128566    6827 utils.go:98] GRPC request: {"target_path":"/data/kubelet/pods/cd261372-c6f5-4eb4-a39e-e8e0bf9a9a1c/volumes/kubernetes.io~csi/lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b/mount","volume_id":"lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b"}
time="2025-06-05T16:44:17+08:00" level=info msg="Unmount /data/kubelet/pods/cd261372-c6f5-4eb4-a39e-e8e0bf9a9a1c/volumes/kubernetes.io~csi/lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b/mount, the command is umount [/data/kubelet/pods/cd261372-c6f5-4eb4-a39e-e8e0bf9a9a1c/volumes/kubernetes.io~csi/lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b/mount]"
I0605 16:44:17.145145    6827 utils.go:103] GRPC response: {}
I0605 16:44:17.227821    6827 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0605 16:44:17.227834    6827 utils.go:98] GRPC request: {}
I0605 16:44:17.227881    6827 utils.go:103] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":3}}}]}
I0605 16:44:17.228584    6827 utils.go:97] GRPC call: /csi.v1.Node/NodeUnstageVolume
I0605 16:44:17.228596    6827 utils.go:98] GRPC request: {"staging_target_path":"/data/kubelet/plugins/kubernetes.io/csi/pv/lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b/globalmount","volume_id":"lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b"}
I0605 16:44:17.228635    6827 utils.go:103] GRPC response: {}
I0605 16:45:15.122100    6827 utils.go:97] GRPC call: /csi.v1.Controller/DeleteVolume
I0605 16:45:15.122119    6827 utils.go:98] GRPC request: {"volume_id":"lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b"}
time="2025-06-05T16:45:15+08:00" level=info msg="DeleteVolume: Successfully deleting volume: lvm-0a7a8cc3-6db3-4040-a5c9-e7b03ae6265b"
I0605 16:45:15.122227    6827 utils.go:103] GRPC response: {}

**Comment by huww98** [comment]
不太理解为啥。从日志看是走到了DeleteVolume的，按理是可以删掉的。

你可以试试从仓库里的helm chart安装最新版

**Comment by comeonbabydontbeshy** [comment]
> 不太理解为啥。从日志看是走到了DeleteVolume的，按理是可以删掉的。
> 
> 你可以试试从仓库里的helm chart安装最新版

还有请问下非阿里云环境，自建的k8s上支持部署local-lvm吗
