### ISSUE TITLE
lvm expand error

### ISSUE THREAD

**Issue by dabaooline** [kubernetes-sigs/alibaba-cloud-csi-driver#515]
I expand lvm volume to a large size that the node has no aviable size.
Now this seems has no problem for pod's running.
But after a while, the pod restart beause of himself bug.  It can't restart. Alway on status ```ContainerCreating```.

Although the node has no aviable size to expand, but i think we shouldn't  prevent  pod restart.

**Comment by dabaooline** [comment]
Hello @mowangdk 
Another Question:
Have we achieved  lvm schedule (or called pvc schedule)?  I didn't find any information

![image](https://user-images.githubusercontent.com/12897508/131436273-50c190b1-94f5-4ff4-8726-c0a4f8c2212c.png)


Thankyou.

**Comment by mowangdk** [comment]
> Hello @mowangdk
> Another Question:
> Have we achieved lvm schedule (or called pvc schedule)? I didn't find any information
> 
> ![image](https://user-images.githubusercontent.com/12897508/131436273-50c190b1-94f5-4ff4-8726-c0a4f8c2212c.png)
> 
> Thankyou.

We intend to support [storage-capacity](https://kubernetes.io/docs/concepts/storage/storage-capacity/) in next version.
