### ISSUE TITLE
Disk driver /host/etc/kubernetes/volumes/disk/ cache

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/alibaba-cloud-csi-driver#522]
I've noticed that the Disk CSI driver puts its VolumeID -> Device name cache in `/etc/kubernetes/volumes/disk/` on the host. Is it necessary? I can see that the driver is able to find a device for a volume ID in `GetDeviceByVolumeID`, so why does it need a persistent cache? Can be the cache in memory only and refreshed via `GetDeviceByVolumeID` when a function asks for a missing entry?

In addition, in Alibaba console I can see that the API knows device name of a disk when it's attached to an instance. `ControllerPublish` can get this information from cloud API and return it as `publish_context`, which will be then passed to `NodePublish` / `NodeStage`. So Kubernetes itself could keep the device name for the driver.

I am afraid that the cache can get stale, e.g. when a node is rebooted without detaching all volumes. And since all information in it could be found elsewhere, can we remove it?

In addition, I can see that `/host/etc/kubernetes/volumes/disk/remove` only grows, after few days/months/years it can be really big. It looks like it's a history of VolumeIDs -> DeviceNames. Can a line in a driver log serve the same purpose?

**Comment by fredkan** [comment]
> I've noticed that the Disk CSI driver puts its VolumeID -> Device name cache in `/etc/kubernetes/volumes/disk/` on the host. Is it necessary? I can see that the driver is able to find a device for a volume ID in `GetDeviceByVolumeID`, so why does it need a persistent cache? Can be the cache in memory only and refreshed via `GetDeviceByVolumeID` when a function asks for a missing entry?
> 
> In addition, in Alibaba console I can see that the API knows device name of a disk when it's attached to an instance. `ControllerPublish` can get this information from cloud API and return it as `publish_context`, which will be then passed to `NodePublish` / `NodeStage`. So Kubernetes itself could keep the device name for the driver.
> 
> I am afraid that the cache can get stale, e.g. when a node is rebooted without detaching all volumes. And since all information in it could be found elsewhere, can we remove it?
> 
> In addition, I can see that `/host/etc/kubernetes/volumes/disk/remove` only grows, after few days/months/years it can be really big. It looks like it's a history of VolumeIDs -> DeviceNames. Can a line in a driver log serve the same purpose?

It's the historical reasons: the old disk cannot find the device with GetDeviceByVolumeID.
if one disk is created before a date, it is not support serial number.
and also the console(api) device name is inaccurate, cannot be used.

currently, we use GetDeviceByVolumeID in the first priority, and if the disk is old one, it will use "diff" to find the device.
and the cache is only to validate the mount info.

**Comment by jia-jerry** [comment]
So now we could find the device via `GetDeviceByVolumeID` now, right?

**Comment by jsafrane** [comment]
Will the "old" disk go away eventually? It would be great to remove the internal cache, as it can be out of sync too. And nothing cleans it up after node reboots.
