### ISSUE TITLE
External Provisioner v3.0.0

### ISSUE THREAD

**Issue by yuvalman** [kubernetes-sigs/alibaba-cloud-csi-driver#523]
Hi,
Is AliCloud CSI plugin work well with [external provisioner v3.0.0](https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.0.0)

**Comment by mowangdk** [comment]
> Hi,
> Is AliCloud CSI plugin work well with [external provisioner v3.0.0](https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.0.0)

Sorry, we currently have no test with external-provisioner v3.0.0, we will upgrade it recently
