### ISSUE TITLE
Fail to mount disk to pod in NodePublishVolume

### ISSUE THREAD

**Issue by jia-jerry** [kubernetes-sigs/alibaba-cloud-csi-driver#544]
This issue happens sporadically. 
k8s version: 1.20.9
csi plugin version: v1.18.8.45-1c5d2cd1-aliyun
logs:
```
I1013 13:38:39.411455      10 utils.go:98] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c/globalmount","target_path":"/var/lib/kubelet/pods/104db0e1-1ed1-4594-bd95-5e70f70ece93/volumes/kubernetes.io~csi/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"encrypted":"true","readOnly":"false","storage.kubernetes.io/csiProvisionerIdentity":"1634045603068-1847-diskplugin.csi.alibabacloud.com","type":"cloud_ssd"},"volume_id":"d-d7ob1p0o20goqpywztm5"}
time="2021-10-13T13:38:39+08:00" level=info msg="NodePublishVolume: Starting Mount Volume d-d7ob1p0o20goqpywztm5, source /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c/globalmount > target /var/lib/kubelet/pods/104db0e1-1ed1-4594-bd95-5e70f70ece93/volumes/kubernetes.io~csi/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c/mount"
E1013 13:38:39.412652      10 utils.go:101] GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c/globalmount: no such file or directory
```

After I login the node, I found there is no globalmount file. 
```
[root@csi-disk-plugin-alicloud-m4zhn pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c]# ls
vol_data.json
[root@csi-disk-plugin-alicloud-m4zhn pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c]# pwd
/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c
[root@csi-disk-plugin-alicloud-m4zhn pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c]# cat vol_data.json
{"driverName":"diskplugin.csi.alibabacloud.com","volumeHandle":"d-d7ob1p0o20goqpywztm5"}
[root@csi-disk-plugin-alicloud-m4zhn pv-dev40-a-8d445de6-17f1-434b-bbe2-28ce4c58b914]# ls /dev/vd*
/dev/vda   /dev/vda2  /dev/vda4  /dev/vdc  /dev/vde  /dev/vdg  /dev/vdi  /dev/vdk  /dev/vdm  /dev/vdo
/dev/vda1  /dev/vda3  /dev/vdb   /dev/vdd  /dev/vdf  /dev/vdh  /dev/vdj  /dev/vdl  /dev/vdn  /dev/vdp
```
I checked the alreadly 15 volumes are attached to the current node, this is expected.

Not sure why `NodeStageVolume` failed to mount /dev/vd* to /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-dev40-a-ea366c1c-09d0-4364-927b-20e5fd466b5c/globalmount.

**Comment by mowangdk** [comment]
> > Please upgrade csiplugin & csiprovisioner version to the newest(v1.20.5-ff6490f-aliyun)
> 
> I was asking because csi-provisioner is mentioned here. Good to hear that it is not involved. And yes, it is a self-build k8s cluster on ecs.

your cluster is quite special, the versions of these two components should be the same by default。please upgrade the csi-plugin first and try it again

**Comment by jia-jerry** [comment]
@mowangdk , this issue still exists after csi plugin is upgraded. https://github.com/gardener/gardener-extension-provider-alicloud/pull/370

**Comment by jia-jerry** [comment]
It still failed.
This issue only happens when a pod is recreated at the same node.

From the log, we could see following fuctions are called:
`NodeUnpublishVolume -> NodeUnstageVolume -> NodePublishVolume `

This is not correct. we expect the function call sequence is:
`NodeUnpublishVolume -> NodeUnstageVolume -> NodeStageVolume -> NodePublishVolume `

**Comment by mowangdk** [comment]
> It still failed. This issue only happens when a pod is recreated at the same node.
> 
> From the log, we could see following fuctions are called: `NodeUnpublishVolume -> NodeUnstageVolume -> NodePublishVolume `
> 
> This is not correct. we expect the function call sequence is: `NodeUnpublishVolume -> NodeUnstageVolume -> NodeStageVolume -> NodePublishVolume `
> 
> I checked log from kubelet and found it is caused concurrent detach in `NodeUnstageVolume` step. As kubelet regarded `NodeUnstageVolume` was not finished as it was failed, so it will not call `NodeStageVolume`.

https://github.com/kubernetes/kubernetes/issues/102779, ptal this issue

**Comment by mowangdk** [comment]
@jia-jerry Is this problem solved?  this problem is no longer exists in kubernetes 1.22 . Upgrade the cluster should be worked too

**Comment by jia-jerry** [comment]
Will close it for now. Thank you.
