### ISSUE TITLE
Failed to mount disk for pod, disk created successfully

### ISSUE THREAD

**Issue by hyt05** [kubernetes-sigs/alibaba-cloud-csi-driver#591]
#### What happened:
Failed to mount disk for pod, disk created successfully
#### Environment:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration:
`Alibaba Cloud ECS`
- OS (e.g: `cat /etc/os-release`):
`NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`
- Kernel (e.g. `uname -a`):
`Linux ali-hk-k3s 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
`k3s`

implement  `kubectl logs -f --tail 30 -n kube-system csi-provisioner-6cddffdf66-vdjpl external-disk-attacher`
`E0114 04:00:10.387354       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0114 04:00:10.388155       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
I0114 04:00:11.387466       1 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from k8s.io/client-go/informers/factory.go:135
I0114 04:00:11.388524       1 reflector.go:188] Listing and watching *v1beta1.CSINode from k8s.io/client-go/informers/factory.go:135
E0114 04:00:11.390808       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0114 04:00:11.390873       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
I0114 04:00:12.390923       1 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from k8s.io/client-go/informers/factory.go:135
I0114 04:00:12.392003       1 reflector.go:188] Listing and watching *v1beta1.CSINode from k8s.io/client-go/informers/factory.go:135
E0114 04:00:12.394029       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0114 04:00:12.394516       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
I0114 04:00:13.394145       1 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from k8s.io/client-go/informers/factory.go:135
I0114 04:00:13.395211       1 reflector.go:188] Listing and watching *v1beta1.CSINode from k8s.io/client-go/informers/factory.go:135
E0114 04:00:13.396579       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0114 04:00:13.396992       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
`

**Comment by mowangdk** [comment]
Support for 1.22 not published yet. please wait for some times

**Comment by hyt05** [comment]
> 尚未发布对 1.22 的支持。请稍等片刻

Please @ me when you support, thanks

**Comment by yang-wang11** [comment]
the same occurrence on my cluster(1.22.3), the external-disk-attacher tried to get `v1beta1.VolumeAttachment` but the version change from  `v1beta1` to `v1`
```
I0204 15:55:15.360007       9 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-diskplugin-csi-alibabacloud-com
I0204 15:55:15.658441       9 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
I0204 15:55:15.660302       9 reflector.go:188] Listing and watching *v1beta1.CSINode from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
E0204 15:55:15.660371       9 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0204 15:55:15.660841       9 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.CSINode: the server could not find the requested resource
```
I guess it relates to https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/
@mowangdk Could you mind telling us what version should we use now? thanks.

**Comment by mowangdk** [comment]
> the same occurrence on my cluster(1.22.3), the external-disk-attacher tried to list `v1beta1.VolumeAttachment` but the version change from `v1beta1` to `v1`
> 
> ```
> I0204 15:55:15.360007       9 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-diskplugin-csi-alibabacloud-com
> I0204 15:55:15.658441       9 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
> I0204 15:55:15.660302       9 reflector.go:188] Listing and watching *v1beta1.CSINode from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
> E0204 15:55:15.660371       9 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
> E0204 15:55:15.660841       9 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.CSINode: the server could not find the requested resource
> ```
> 
> it relates to https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/, see below
> 
> ```
> The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22.
> 
> Migrate manifests and API clients to use the storage.k8s.io/v1 API version
> CSIDriver is available in storage.k8s.io/v1 since v1.19.
> CSINode is available in storage.k8s.io/v1 since v1.17
> StorageClass is available in storage.k8s.io/v1 since v1.6
> VolumeAttachment is available in storage.k8s.io/v1 v1.13
> All existing persisted objects are accessible via the new APIs
> No notable changes
> ```
> 
> @mowangdk Could you mind telling us what version should we use now? thanks.

pls use yamls under https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/ack, k8s 1.22 is now supported

**Comment by mowangdk** [comment]
> > 尚未发布对 1.22 的支持。请稍等片刻
> 
> Please @ me when you support, thanks

@hyt05  pls use yamls under https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/ack, k8s 1.22 is now supported

**Comment by hyt05** [comment]
> 

好的谢谢

**Comment by hyt05** [comment]
> > > 尚未发布对 1.22 的支持。请稍等片刻
> > 
> > 
> > 支持时请@我，谢谢
> 
> @hyt05请在https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/ack 下使用 yamls ，现在支持 k8s 1.22

感谢
