### ISSUE TITLE
timeout expired waiting for volumes to attach or mount for pod xxx

### ISSUE THREAD

**Issue by hfrzhanghao** [kubernetes-sigs/alibaba-cloud-csi-driver#60]
1、$ cd build && sh build-oss.sh
2、# kubectl create -f ./deploy/csidriver.yaml  --validate=false
3、# kubectl create -f ./deploy/oss/oss-plugin.yaml

4、查看CSIDriver状态：
[root@vm-zdyh3linux-1 deploy]# kubectl describe CSIDriver ossplugin.csi.alibabacloud.com
Name:         ossplugin.csi.alibabacloud.com
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  csi.storage.k8s.io/v1alpha1
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2019-08-08T02:23:17Z
  Generation:          1
  Resource Version:    393449
  Self Link:           /apis/csi.storage.k8s.io/v1alpha1/csidrivers/ossplugin.csi.alibabacloud.com
  UID:                 7bba4fe4-b983-11e9-ad8e-525400ccffd1
Spec:
  Attach Required:  false
Events:             <none>
[root@vm-zdyh3linux-1 deploy]# 

5、修改deploy.yaml中pv的bucket url akid aksecret(这几项都是从页面中获取)，otherOpts没有改；

6、kubectl create -f deply.yaml
pv和pvc绑定成功，但是pod的状态出错：timeout expired waiting for volumes to attach or mount for pod
[root@vm-zdyh3linux-1 deploy]# kubectl describe pod deployment-oss-57d5695645-7gtcn
Name:               deployment-oss-57d5695645-7gtcn
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               vm-zdyh3linux-1/192.168.0.181
Start Time:         Thu, 08 Aug 2019 10:57:33 +0800
Labels:             app=nginx
                    pod-template-hash=1381251201
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/deployment-oss-57d5695645
Containers:
  nginx:
    Container ID:
    Image:          nginx:1.7.9
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from oss-pvc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zrxm4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  oss-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  oss-pvc
    ReadOnly:   false
  default-token-zrxm4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zrxm4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age               From                      Message
  ----     ------              ----              ----                      -------
  Warning  FailedScheduling    9m (x2 over 9m)   default-scheduler         pod has unbound PersistentVolumeClaims (repeated 3 times)
  Warning  FailedScheduling    9m                default-scheduler         AssumePod failed: pod 44ac908f-b988-11e9-ad8e-525400ccffd1 is in the cache, so can't be assumed
  Normal   Scheduled           9m                default-scheduler         Successfully assigned default/deployment-oss-57d5695645-7gtcn to vm-zdyh3linux-1
  Warning  FailedMount         1m (x4 over 7m)   kubelet, vm-zdyh3linux-1  Unable to mount volumes for pod "deployment-oss-57d5695645-7gtcn_default(44ac908f-b988-11e9-ad8e-525400ccffd1)": timeout expired waiting for volumes to attach or mount for pod "default"/"deployment-oss-57d5695645-7gtcn". list of unmounted volumes=[oss-pvc]. list of unattached volumes=[oss-pvc default-token-zrxm4]
  Warning  FailedAttachVolume  29s (x5 over 9m)  attachdetach-controller   AttachVolume.Attach failed for volume "oss-csi-pv" : attachment timeout for volume data-id
[root@vm-zdyh3linux-1 deploy]#

**Comment by fredkan** [comment]
set --enable-controller-attach-detach=false in kubelet config.

**Comment by fredkan** [comment]
CSIDriver is default enabled in 1.14.3, it is better to use k8s 1.14.

**Comment by fredkan** [comment]
if there is still problem, reopen this issue. Thanks.
