### ISSUE TITLE
Liveness probe failed

### ISSUE THREAD

**Issue by Ithrael** [kubernetes-sigs/alibaba-cloud-csi-driver#614]
#### What happened:
csi-plugin pod error，it's Events 
Events:
  Type     Reason        Age                   From     Message
  ----     ------        ----                  ----     -------
  Warning  Unhealthy     26m (x351 over 11h)   kubelet  Liveness probe failed: Get http://192.168.100.146:11260/healthz: dial tcp 192.168.100.146:11260: connect: connection refused
  Warning  BackOffStart  11m (x2054 over 11h)  kubelet  the failed container exited with ExitCode: 2
  Warning  BackOffStart  64s (x2079 over 11h)  kubelet  Back-off restarting failed container

#### What you expected to happen:
csi-plugin pod  running normally

#### How to reproduce it (as minimally and precisely as possible):
The results of this got so I reference  https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/oss.md

#### Anything else we need to know?:
None

#### Environment:
- Kubernetes version (use `kubectl version`):  
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:   
None
- OS (e.g: `cat /etc/os-release`): 
Ubuntu 18.04
- Kernel (e.g. `uname -a`):  
Linux i-qgr7zvo9 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:  
kubeadm
- Network plugin and version (if this is a network-related bug):  
flannel
- Others:
None

**Comment by Ithrael** [comment]
@fredkan

**Comment by Ithrael** [comment]
补充：
/var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com 目录下没有csi.sock文件
![image](https://user-images.githubusercontent.com/38208715/156099121-3d32fecf-6cff-4607-8833-9942df88a2d0.png)

**Comment by cuericlee** [comment]
### collect logs from the node with following script.

curl -L http://aliacs-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/diagnose/diagnose_k8s.sh | bash -
