### ISSUE TITLE
Lvm CSI Plugin support for k8s1.20+

### ISSUE THREAD

**Issue by lifighter** [kubernetes-sigs/alibaba-cloud-csi-driver#619]
Using Kubernetes v1.21.2, getting "unexpected error getting claim reference: selfLink was empty, can't make reference". There is a repair for ack & disk https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/commit/ac3e1768d5796f5fae2b983c2af327544082addf, but doesnot have a repair for lvm. Expect for that.

**Comment by git-yww** [comment]
I am facing exactly the same issue. Is there any workaround for this? @lifighter
