### ISSUE TITLE
自建k8s1.18集群oss的pvc方式失败

### ISSUE THREAD

**Issue by dejavu6** [kubernetes-sigs/alibaba-cloud-csi-driver#661]
#### What happened:
自建k8s集群1.18，在之上按照oss文档完成csi插件、pv、pvc的创建，但是到使用nginx的pod的时候，会报找不到插件。

<img width="650" alt="image" src="https://user-images.githubusercontent.com/26924629/169445525-096dbc69-d3fe-4292-a27e-82dad320652b.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/26924629/169445599-e2d59c5a-6996-4922-95e0-1627a5ee9685.png">
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/26924629/169445675-a1e9b7e2-9311-47eb-9cd8-9e230aacd2d0.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/26924629/169445728-f0627bb3-8e6b-4886-9b6d-470ba863409e.png">
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/26924629/169445793-ea329858-9abb-4b7d-bcfa-0a5a5b0305aa.png">

#### What you expected to happen:
期待pod能使用oss的pvc

#### How to reproduce it (as minimally and precisely as possible):
1. 自建k8s1.18集群
2. 安装doc/oss.md进行安装

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18.20
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009
- Kernel (e.g. `uname -a`): 5.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Oct 26 11:43:20 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): csi-node-driver-registrar-v1.2.0 csi-plugin-v1.18.8.47-906bd535-aliyun
- Others:

**Comment by mowangdk** [comment]
csi 插件的部署状态有问题, csi 没有注册到 kubelet, 导致这个问题, 查看一下 kubelet 日志
