### ISSUE TITLE
自建的K8S的Nas的addon.token.config没有找到对应的保存secrect的YAML文档

### ISSUE THREAD

**Issue by dwzkit** [kubernetes-sigs/alibaba-cloud-csi-driver#707]
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/nas.md

我是自建的K8S（所有的节点都是在阿里云的同一个区的ECS），计划按照上述文档的安装步骤安装：nas-plugin和nas-provisioner，各自对应的YAML文件路径如下：
nas-plugin：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/nas/nas-plugin.yaml
nas-provisioner：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/nas/nas-provisioner.yaml
其中nas-provisioner的安装有几个参数不太明白，想请教一下：
        - name: addon-token
          secret:
            defaultMode: 420
            optional: true
            items:
              - key: addon.token.config
                path: token-config
            secretName: addon.csi.token

这个addon.token.config我理解应该是要把我的阿里云账户对应的AccessKeyID以及AccessKeySecret等参数以secrect的形式保存在自建的K8S中。
但是在github上好像没有找到对应的保存secrect的YAML文档，不知道应该要保存哪些参数以及以什么格式保存，可以提供样本参考一下吗？

**Comment by mowangdk** [comment]
群里已回

**Comment by dwzkit** [comment]
感谢钉钉答疑！

**Comment by zhengbucuo888** [comment]
不粘贴出来吗？我也需要

**Comment by fungaren** [comment]
贵司对开源的理解 = 群里已回。那你开源个 🔨

**Comment by zhengbucuo888** [comment]
> 

哈哈，我已经找到了对应的文档了。

**Comment by mowangdk** [comment]
@fungaren  您说的没错, 这里我统一回复下.  这个addon secrets 是针对 ack 集群提供的 optional 的 secrets. 该 secrets 是由 ack 闭源组件生成的加密临时 token. 不适用于自建集群. 自建集群建议通过注册集群/node ram role 的方式进行授权
