### ISSUE TITLE
(*CSIDriver).AddVolumeCapabilityAccessModes(0x0, {0xc000713e5c, 0x1, 0x10?}) 

### ISSUE THREAD

**Issue by Peakchen** [kubernetes-sigs/alibaba-cloud-csi-driver#711]
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

panic: runtime error: invalid memory address or nil pointer dereference

**Comment by mowangdk** [comment]
Please provide more information about this issue

**Comment by cuericlee** [comment]
Pls provide env infomation!

Environment:
Kubernetes version (use kubectl version):
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Network plugin and version (if this is a network-related bug):
Others:
