### ISSUE TITLE
部署 csi-plugin.yaml 出现异常

### ISSUE THREAD

**Issue by kevinxjm** [kubernetes-sigs/alibaba-cloud-csi-driver#72]
unable to recognize "csi-plugin.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta"

版本：
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-04-22T11:34:20Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by fredkan** [comment]
csi需要在1.14版本上部署。

**Comment by kevinxjm** [comment]
> csi需要在1.14版本上部署。

帮助文档看到可以支持之前的版本：

Kubernetes | CSI Version | CSI Status
-- | -- | --
v1.9 | v0.1 | Alpha
v1.10 | v0.2 | Beta
v1.11 | v0.3 | Beta
v1.12 | v0.3 | Beta
v1.13 | v1.0.0 | GA
v1.14 | v1.0.0 | GA

**Comment by fredkan** [comment]
如果还有问题，请提新issue，谢谢。
