### ISSUE TITLE
csi-provisioner报错：ErrorCode: InvalidAccessKeyId.NotFound

### ISSUE THREAD

**Issue by iceblove** [kubernetes-sigs/alibaba-cloud-csi-driver#722]
用alibaba-cloud-csi-driver下的deploy/rbac.yaml、deploy/ack/csi-plugin.yaml, deploy/csi-provisioner.yaml 部署，然后把alicloud-disk-essd设置为默认sc，用Helm安装 apisix时pvc一直pending状态

看日志：
kubectl logs -f csi-provisioner-dd5d4cc55-chqt6 -n ingress-apisix

如下：

I1227 07:21:44.769752      10 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"ingress-apisix", Name:"data-apisix-etcd-2", UID:"05f5cef3-443f-4f14-a2f9-3a7453ae07da", APIVersion:"v1", ResourceVersion:"1109948", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "alicloud-disk-essd": rpc error: code = Internal desc = SDK.ServerError
ErrorCode: InvalidAccessKeyId.NotFound
Recommend: https://next.api.aliyun.com/troubleshoot?q=InvalidAccessKeyId.NotFound&product=Ecs
RequestId: 3B9EA20D-E083-57CE-A32E-2E661945E266
Message: Specified access key is not found.

#### Environment:
- Kubernetes version (1.25.5):
- Cloud provider or hardware configuration: aliyun， ECS ，自建K8S
- OS (e.g: `cat /etc/os-release`): debian 11.4
- Kernel (e.g. `uname -a`): Linux master.k8s.weilaishuke 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
- Install tools: kubeadm, kubelet, kubectl , helm 
- Network plugin and version (if this is a network-related bug): calico-3.24.5
- Others:

**Comment by mowangdk** [comment]
报错说的是 accesskey 异常, 请问这边确认 aksk 还生效吗?

**Comment by cuericlee** [comment]
As for self-build cluster, pls use register cluster to install latest version of CSI addon.
https://help.aliyun.com/document_detail/335175.html
