### ISSUE TITLE
自建k8s无法使用OSS插件

### ISSUE THREAD

**Issue by helloxubo** [kubernetes-sigs/alibaba-cloud-csi-driver#736]
自建的K8S在使用的OSS时日志中提示：“Failed connect to 100.100.100.200:80; Connection timed out”。
经排查，IP”100.100.100.200“”只有阿里云的服务器才能连接。其它的服务器无法访问。
可有其它的解决办法，谢谢？

**Comment by cuericlee** [comment]
Pls leverage register cluster to install latest CSI from addon center for self-build K8s cluster.
https://help.aliyun.com/document_detail/335175.html

**Comment by zhangzhenhuajack** [comment]
### 第一步：参考文档：https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/v1.1.6/docs/oss.md   安装oss-csi-plugin 插件；
1）从这个文档中可以知道 kubectl create -f ./deploy/oss/oss-plugin.yaml  进行发布，但是发不完之后，观察 kubectl -n kube-system logs -f csi-plugin-jpw6n -c csi-plugin  报“Failed connect to 100.100.100.200:80; Connection timed out”。 错误，并且有一些centos的命令操作，所以猜想可能镜像不对。

2）通过上面的文档$ cd build && sh build-oss.sh 也知道了如何编译源码，于是乎查看 Dockfile和entrypoint.sh 根据node的操作系统的版本做了如下修改：
![image](https://user-images.githubusercontent.com/11462004/223998586-074b83df-d509-4e77-bf65-634b8cc555b2.png)
![image](https://user-images.githubusercontent.com/11462004/223998784-2653c2c9-2424-4834-a521-9c6a35d8ccc1.png)
![image](https://user-images.githubusercontent.com/11462004/223998855-ee844bf4-f543-431c-b50d-13ac3de5289e.png)

**Comment by majiajun7** [comment]
+1 我也遇到此问题

**Comment by AlbeeSo** [comment]
> +1 我也遇到此问题 

@majiajun7 方便问问现在您使用的CSI版本吗？确认一下是否已经带上该bugfix: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/825/files
