### ISSUE TITLE
Cannot find the exact documentation explaining available options in`StorageClass.parameters`

### ISSUE THREAD

**Issue by nashtsai** [kubernetes-sigs/alibaba-cloud-csi-driver#745]
Hi there,

I am looking the `storageclass.parameters` for disk CSI (https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/disk.md), it appears that I can only spot a few from examples, could you please provide a reference doc that's comparable to following:

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#createvolume-parameters
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md

**Comment by mowangdk** [comment]
Currently there is no detailed documentation on github, you can refer to our official website for detailed documentation. https://help.aliyun.com/document_detail/134859.html#section-qlr-jkq-hi2
