### ISSUE TITLE
The specified parameter "Size" is not valid

### ISSUE THREAD

**Issue by 0haha** [kubernetes-sigs/alibaba-cloud-csi-driver#767]
when I try to execute the following step in this essay:https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/disk.md 
However , I fail. And it comes to the following result:
failed to provision volume with StorageClass "rainbondvolumerwx": rpc error: code = Internal desc = SDK.ServerError ErrorCode: InvalidParameter Recommend: https://next.api.aliyun.com/troubleshoot?q=InvalidParameter&product=Ecs RequestId: E87401CA-165D-5ED0-A355-E52CC16DB12B Message: The specified parameter "Size" is not valid.

**Comment by mowangdk** [comment]
https://help.aliyun.com/document_detail/286495.htm#section-r6k-e7i-l78
