### ISSUE TITLE
不知道该使用哪个分支，readme文档完全对不上

### ISSUE THREAD

**Issue by 0haha** [kubernetes-sigs/alibaba-cloud-csi-driver#768]

**Comment by mowangdk** [comment]
请问需求是什么?

**Comment by 0haha** [comment]
https://v5.6-docs.rainbond.com/docs/v5.3/user-operations/storage/ali-disk/#storageclass-%E7%9A%84%E5%88%9B%E5%BB%BA
想要照这个实现 自动化分配云盘disk作为存储。

**Comment by mowangdk** [comment]
> https://v5.6-docs.rainbond.com/docs/v5.3/user-operations/storage/ali-disk/#storageclass-%E7%9A%84%E5%88%9B%E5%BB%BA 想要照这个实现 自动化分配云盘disk作为存储。

现在问题是 storageclass 创建不出来? 还是什么?

**Comment by cataglyphis** [comment]
deploy 里 ecs 和 nonecs 的区别是啥？

**Comment by mowangdk** [comment]
> deploy 里 ecs 和 nonecs 的区别是啥？

 ecs 是使用阿里云 ecs 自建集群使用的 yaml, non ecs 是线下 IDC 自建集群使用的 yaml
