### ISSUE TITLE
Can't build arm binary on arm platform when use build-local.sh

### ISSUE THREAD

**Issue by xuanyunhui** [kubernetes-sigs/alibaba-cloud-csi-driver#779]
#### What happened:
Can't build arm binary on arm platform when use build-local.sh

#### What you expected to happen:
Detect arch for platform when build-local.sh

#### How to reproduce it (as minimally and precisely as possible):
Remove `export GOARCH="amd64"` line in build-local.sh

**Comment by mowangdk** [comment]
you can build image with https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/build/build-all-multi.sh, support amd & arm archs

**Comment by xuanyunhui** [comment]
> you can build image with https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/build/build-all-multi.sh, support amd & arm archs

Yes, I can build an image for amd and arm or other, but I want to build binary only in some upstream ci cases.

**Comment by mowangdk** [comment]
> > you can build image with https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/build/build-all-multi.sh, support amd & arm archs
> 
> Yes, I can build an image for amd and arm or other, but I want to build binary only in some upstream ci cases.

binary build can refers to dockerfile: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/build/multi/Dockerfile.multi
