### ISSUE TITLE
Pod stuck in containercreating state with the event MountVolume.MountDevice failed for volume "d-0xi32xzgwfsx5bfkwjds" : rpc error: code = Aborted desc = NodeStageVolume: Attach volume: d-0xi32xzgwfsx5bfkwjds with error: "AttachDisk: disk device cannot be found in node, diskid: d-0xi32xzgwfsx5bfkwjds, devicenName:"

### ISSUE THREAD

**Issue by chetanatole** [kubernetes-sigs/alibaba-cloud-csi-driver#780]
**What happened:**
Have deployed a pod-pvc pair, the pvc makes use of alicloud-disk-essd storageclass. When the pod is deployed it stucks in ContainerCreating state and the events shows following:
```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               53m                  default-scheduler        Successfully assigned ca-test/test-pod to rke2-worker-03
  Normal   SuccessfulAttachVolume  53m                  attachdetach-controller  AttachVolume.Attach succeeded for volume "d-0xi32xzgwfsx5bfkwjds"
  Warning  FailedMount             53m                  kubelet                  MountVolume.MountDevice failed for volume "d-0xi32xzgwfsx5bfkwjds" : rpc error: code = Aborted desc = NodeStageVolume: Attach volume: d-0xi32xzgwfsx5bfkwjds with error: rpc error: code = Aborted desc = AttachDisk: after attaching to disk, but fail to get mounted device, will retry later
  Warning  FailedMount             17m (x10 over 51m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-5p89z data]: timed out waiting for the condition
  Warning  FailedMount             12m (x8 over 49m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-5p89z]: timed out waiting for the condition
  Warning  FailedMount             107s (x31 over 53m)  kubelet                  MountVolume.MountDevice failed for volume "d-0xi32xzgwfsx5bfkwjds" : rpc error: code = Aborted desc = NodeStageVolume: Attach volume: d-0xi32xzgwfsx5bfkwjds with error: AttachDisk: disk device cannot be found in node, diskid: d-0xi32xzgwfsx5bfkwjds, devicenName:
```

When checked in alibaba cloud console, the disk is seen to be attached to the node.

Storageclass:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"alicloud-disk-essd"},"parameters":{"type":"cloud_essd"},"provisioner":"diskplugin.csi.alibabacloud.com","reclaimPolicy":"Delete"}
  creationTimestamp: "2023-05-22T11:06:46Z"
  name: alicloud-disk-essd
  resourceVersion: "1572931"
  uid: 3c90b495-a9ff-4214-85dc-c81e1d3963ff
parameters:
  type: cloud_essd
provisioner: diskplugin.csi.alibabacloud.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"test-pvc","namespace":"ca-test"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"alicloud-disk-essd"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: diskplugin.csi.alibabacloud.com
    volume.kubernetes.io/storage-provisioner: diskplugin.csi.alibabacloud.com
  creationTimestamp: "2023-05-30T08:03:03Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: test-pvc
  namespace: ca-test
  resourceVersion: "2907087"
  uid: 47e9fb2b-27d8-4910-ba6d-cc00b9aea277
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: alicloud-disk-essd
  volumeMode: Filesystem
  volumeName: d-0xi32xzgwfsx5bfkwjds
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
```

Pod
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"test-pod","namespace":"ca-test"},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/voltest","name":"data"}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"test-pvc"}}]}}
  creationTimestamp: "2023-05-30T08:14:56Z"
  name: test-pod
  namespace: ca-test
  resourceVersion: "2911265"
  uid: b3e33d69-5971-455e-80f8-19fda9c36083
spec:
  containers:
  - image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /voltest
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5p89z
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: rke2-worker-03
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: test-pvc
  - name: kube-api-access-5p89z
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T08:14:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T08:14:56Z"
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T08:14:56Z"
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T08:14:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: nginx:1.14.2
    imageID: ""
    lastState: {}
    name: nginx
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.16.95.129
  phase: Pending
  qosClass: BestEffort
  startTime: "2023-05-30T08:14:56Z"

```
**What you expected to happen:**
Volume should be mounted and pod should go in running state.

**Environment:**
- Kubernetes version:
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9+rke2r1", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T19:05:26Z", GoVersion:"go1.19.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
K8S Cluster on Alibaba Cloud using RKE2
- OS: CentOS Linux 7 (Core)
- Kernel: 3.10.0-1160.88.1.el7.x86_64
- ECS Instance type: ecs.g7.large

**Comment by mowangdk** [comment]
What is the version of the csi plugin in your cluster? and what is the ecs instancetypes

**Comment by chetanatole** [comment]
CSI Plugin: v1.24.9-74f8490-aliyun
ECS Instance type: ecs.g7.large

**Comment by mowangdk** [comment]
Please provide a work order to ebs, this looks like a problem for ebs

**Comment by chetanatole** [comment]
@mowangdk Does the following code looks for dev file for the attached device? 
pkg/disk/cloud.go
![Screenshot 2023-05-31 163021](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/31009167/f7bbc458-4a82-442e-bfc0-37602dc11f0a)

I can see the disk attached to the node
![Screenshot 2023-05-31 164007](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/31009167/1ef57841-e929-497d-b6c5-c3e19b448fe1)

And here's the dev file for the device inside node
![Screenshot 2023-05-31 164054](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/31009167/7507ff21-d230-4c51-8c86-6a944a94d7dc)

**Comment by chetanatole** [comment]
Logs for csi-plugin container
![Screenshot 2023-06-01 110420](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/31009167/85f4fb1b-e7b1-4961-90ac-3d83420be471)

**Comment by mowangdk** [comment]
Please see the output of the command ```ls -l /dev/disk/by-id/ ```

**Comment by chetanatole** [comment]
```
sh-4.2# ls -l /dev/disk/by-id/
total 0
lrwxrwxrwx 1 root root  9 May 30 13:53 virtio-0xi2n7t0j0gru8n9vf7b -> ../../vda
lrwxrwxrwx 1 root root 10 May 30 13:53 virtio-0xi2n7t0j0gru8n9vf7b-part1 -> ../../vda1
lrwxrwxrwx 1 root root  9 May 30 16:15 virtio-0xi32xzgwfsx5bfkwjds -> ../../vdb
```

**Comment by mowangdk** [comment]
pls change csi-plugin main container image to version v1.24.10-7ae4421-aliyun
and retry

Chetan Atole ***@***.***> 于2023年6月1日周四 14:43写道：

**Comment by chetanatole** [comment]
Container is failing after image update

Correction:

> CSI Plugin image tag: v1.24.9-74f8490-aliyun

The CSI plugin image that was in use earlier was v1.24.5-39a3970-aliyun
```
[root@rke2-bootstrap ~]# k logs csi-plugin-jmqxv -n kube-system -c csi-plugin
/etc/os-release
Running oss plugin....
Running nas plugin....
Running disk plugin....
Starting deploy oss csi-plugin...
osHost:centos
ossfsVersion:1.88.0
ossfsArch:centos7.0
Check ossfs Version....
Check csiplugin-connector.service....
Starting systemctl enable csiplugin-connector.service.
Starting systemctl restart csiplugin-connector.service.
time="2023-06-01T16:01:34+08:00" level=info msg="Multi CSI Driver Name: oss,nas,disk, nodeID: , endPoints: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock"
time="2023-06-01T16:01:34+08:00" level=info msg="CSI Driver Branch: , Version: , Build time: \n"
time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/controller"
time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/node"
time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/controller"
time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/node"
time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/controller"
time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/node"
time="2023-06-01T16:01:34+08:00" level=info msg="CSI is running status."
time="2023-06-01T16:01:34+08:00" level=info msg="Metric listening on address: /healthz"
W0601 16:01:34.679651   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-06-01T16:01:34+08:00" level=info msg="Driver: ossplugin.csi.alibabacloud.com version: 1.0.0"
time="2023-06-01T16:01:34+08:00" level=info msg="Driver: nasplugin.csi.alibabacloud.com version: 1.0.0"
W0601 16:01:34.680615   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0601 16:01:34.680836   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0601 16:01:34.683187   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0601 16:01:34.683907   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0601 16:01:34.684716   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-06-01T16:01:34+08:00" level=info msg="RetryGetMetaData: successful get metadata instance-id: i-0xiigohy126dfdusppdf"
time="2023-06-01T16:01:34+08:00" level=info msg="Use node id : i-0xiigohy126dfdusppdf"
I0601 16:01:34.684951   12453 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0601 16:01:34.684960   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0601 16:01:34.684965   12453 driver.go:81] Enabling controller service capability: UNKNOWN
time="2023-06-01T16:01:34+08:00" level=info msg="Metric listening on address: /metrics"
W0601 16:01:34.685665   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-06-01T16:01:34+08:00" level=info msg="RetryGetMetaData: successful get metadata instance-id: i-0xiigohy126dfdusppdf"
time="2023-06-01T16:01:34+08:00" level=info msg="Use node id : i-0xiigohy126dfdusppdf"
I0601 16:01:34.685697   12453 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0601 16:01:34.685702   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0601 16:01:34.685706   12453 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0601 16:01:34.685710   12453 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
W0601 16:01:34.685716   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-06-01T16:01:34+08:00" level=info msg="Not found configmap named as csi-plugin under kube-system, with: configmaps \"csi-plugin\" not found"
time="2023-06-01T16:01:34+08:00" level=info msg="AD-Controller is disabled, CSI Disk Plugin running in kubelet mode."
time="2023-06-01T16:01:34+08:00" level=info msg="Describe node rke2-worker-02 and Set RunTimeClass to runc"
time="2023-06-01T16:01:34+08:00" level=info msg="Starting with GlobalConfigVar: region(), zone(), NodeID(), ADControllerEnable(false), DiskTagEnable(false), DiskBdfEnable(false), MetricEnable(true), RunTimeClass(runc), DetachDisabled(false), DetachBeforeDelete(true), ClusterID()"
E0601 16:01:34.687999   12453 driver.go:46] NodeID missing
I0601 16:01:34.688004   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0601 16:01:34.688008   12453 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0601 16:01:34.688012   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0601 16:01:34.688015   12453 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I0601 16:01:34.688019   12453 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
rke2://rke2-worker-02
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x183c7b6]

goroutine 13 [running]:
github.com/kubernetes-csi/drivers/pkg/csi-common.(*CSIDriver).AddControllerServiceCapabilities(0x0, {0xc000459ea4, 0x5, 0x0?})
        /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/driver.go:85 +0x1d6
github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/disk.NewDriver({0x0, 0x0}, {0xc0002f94a0, 0x4b}, 0x0)
        /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/disk/disk.go:113 +0x152
main.main.func4({0xc0002f94a0?, 0x0?})
        /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:208 +0x85
created by main.main
        /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:206 +0x12ea

```

**Comment by mowangdk** [comment]
> Container is failing after image update
> 
> Correction:
> 
> > CSI Plugin image tag: ~v1.24.9-74f8490-aliyun~
> 
> The CSI plugin image that was in use earlier was v1.24.5-39a3970-aliyun
> 
> ```
> [root@rke2-bootstrap ~]# k logs csi-plugin-jmqxv -n kube-system -c csi-plugin
> /etc/os-release
> Running oss plugin....
> Running nas plugin....
> Running disk plugin....
> Starting deploy oss csi-plugin...
> osHost:centos
> ossfsVersion:1.88.0
> ossfsArch:centos7.0
> Check ossfs Version....
> Check csiplugin-connector.service....
> Starting systemctl enable csiplugin-connector.service.
> Starting systemctl restart csiplugin-connector.service.
> time="2023-06-01T16:01:34+08:00" level=info msg="Multi CSI Driver Name: oss,nas,disk, nodeID: , endPoints: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock"
> time="2023-06-01T16:01:34+08:00" level=info msg="CSI Driver Branch: , Version: , Build time: \n"
> time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/controller"
> time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/ossplugin.csi.alibabacloud.com/node"
> time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/controller"
> time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/nasplugin.csi.alibabacloud.com/node"
> time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/controller"
> time="2023-06-01T16:01:34+08:00" level=info msg="Create Stroage Path: /var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/node"
> time="2023-06-01T16:01:34+08:00" level=info msg="CSI is running status."
> time="2023-06-01T16:01:34+08:00" level=info msg="Metric listening on address: /healthz"
> W0601 16:01:34.679651   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> time="2023-06-01T16:01:34+08:00" level=info msg="Driver: ossplugin.csi.alibabacloud.com version: 1.0.0"
> time="2023-06-01T16:01:34+08:00" level=info msg="Driver: nasplugin.csi.alibabacloud.com version: 1.0.0"
> W0601 16:01:34.680615   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0601 16:01:34.680836   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0601 16:01:34.683187   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0601 16:01:34.683907   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0601 16:01:34.684716   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> time="2023-06-01T16:01:34+08:00" level=info msg="RetryGetMetaData: successful get metadata instance-id: i-0xiigohy126dfdusppdf"
> time="2023-06-01T16:01:34+08:00" level=info msg="Use node id : i-0xiigohy126dfdusppdf"
> I0601 16:01:34.684951   12453 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
> I0601 16:01:34.684960   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
> I0601 16:01:34.684965   12453 driver.go:81] Enabling controller service capability: UNKNOWN
> time="2023-06-01T16:01:34+08:00" level=info msg="Metric listening on address: /metrics"
> W0601 16:01:34.685665   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> time="2023-06-01T16:01:34+08:00" level=info msg="RetryGetMetaData: successful get metadata instance-id: i-0xiigohy126dfdusppdf"
> time="2023-06-01T16:01:34+08:00" level=info msg="Use node id : i-0xiigohy126dfdusppdf"
> I0601 16:01:34.685697   12453 driver.go:93] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
> I0601 16:01:34.685702   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
> I0601 16:01:34.685706   12453 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
> I0601 16:01:34.685710   12453 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
> W0601 16:01:34.685716   12453 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> time="2023-06-01T16:01:34+08:00" level=info msg="Not found configmap named as csi-plugin under kube-system, with: configmaps \"csi-plugin\" not found"
> time="2023-06-01T16:01:34+08:00" level=info msg="AD-Controller is disabled, CSI Disk Plugin running in kubelet mode."
> time="2023-06-01T16:01:34+08:00" level=info msg="Describe node rke2-worker-02 and Set RunTimeClass to runc"
> time="2023-06-01T16:01:34+08:00" level=info msg="Starting with GlobalConfigVar: region(), zone(), NodeID(), ADControllerEnable(false), DiskTagEnable(false), DiskBdfEnable(false), MetricEnable(true), RunTimeClass(runc), DetachDisabled(false), DetachBeforeDelete(true), ClusterID()"
> E0601 16:01:34.687999   12453 driver.go:46] NodeID missing
> I0601 16:01:34.688004   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
> I0601 16:01:34.688008   12453 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
> I0601 16:01:34.688012   12453 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
> I0601 16:01:34.688015   12453 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
> I0601 16:01:34.688019   12453 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
> rke2://rke2-worker-02
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x183c7b6]
> 
> goroutine 13 [running]:
> github.com/kubernetes-csi/drivers/pkg/csi-common.(*CSIDriver).AddControllerServiceCapabilities(0x0, {0xc000459ea4, 0x5, 0x0?})
>         /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/driver.go:85 +0x1d6
> github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/disk.NewDriver({0x0, 0x0}, {0xc0002f94a0, 0x4b}, 0x0)
>         /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/disk/disk.go:113 +0x152
> main.main.func4({0xc0002f94a0?, 0x0?})
>         /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:208 +0x85
> created by main.main
>         /go/src/github.com/kubernetes-sigs/alibaba-cloud-csi-driver/main.go:206 +0x12ea
> ```

yaml must be change to https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/deploy/ecs/csi-plugin.yaml. because ENV KUBE_NODE_NAME is necessary.

**Comment by chetanatole** [comment]
Thanks a lot @mowangdk, upgrading the image to latest version resolved the issue!
