### ISSUE TITLE
Can't attach some disks

### ISSUE THREAD

**Issue by maximrub** [kubernetes-sigs/alibaba-cloud-csi-driver#795]
#### What happened:

For some disks I get this error on attach

GRPC error: rpc error: code = Aborted desc = NodeStageVolume: ADController Enabled, but device can't be found:d-t4ni5fbafznyxqgax972Devices [/dev/vdb /dev/vdb1 /dev/vdb2 /dev/vdb3] has more than 1 partition

#### What you expected to happen:

For the disk to be attached

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Alibaba cloud
- OS (e.g: `cat /etc/os-release`): Aliyun Linux v3
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mowangdk** [comment]
@maximrub Partitioned cloud drives are not supported in the k8s system, just as you cannot declare multiple volumeDevices for a single volume in a pod

**Comment by maximrub** [comment]
Hi @mowangdk, do you know why or when disks are created as multi-partitioned? the source disks are always disks created during ecs instance creation or K8s node. we take a snapshot of them, create a disk from them and attach the new disks

**Comment by mowangdk** [comment]
@maximrub  The first thing you need to check is whether the partition was made before or after the snapshot of the cloud. 

Pre-snapshot partitioning: There are many different scenarios, either the partition was made manually on ecs, or a configuration was written in the ecs console to automatically partition the mounted cloud disk

Post-snapshot partitioning: AFAIK, openebs is a component that can automatically partition a cloud drive

**Comment by maximrub** [comment]
Hi  @mowangdk

**Comment by maximrub** [comment]
Hi @mowangdk 
The Alibaba support team just responded to my ticket, they say

For the ubuntu22.04 official image, this is a normal phenomenon. There are 3 partitions pre-set in the image. As long as all servers use the Ubuntu22.04 image, the system disk will have 3 partitions by default.

Part of the image has 3 partitions. Here you use the ubuntu22.04 image. If you use the centos7 image, there is only one partition.

so all ubuntu 22 images can never be attached to K8s?

**Comment by mowangdk** [comment]
@maximrub  I understand that only the system disk will be partitioned, is the cloud disk you made a snapshot of the system disk? The normal creation of a pvc/pv here does not automatically partition.

**Comment by maximrub** [comment]
@mowangdk this is the os disks output for df -Th && lsblk

`Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs  743M  1.1M  742M   1% /run
/dev/vda3      ext4    40G  3.2G   35G   9% /
tmpfs          tmpfs  3.7G     0  3.7G   0% /dev/shm
tmpfs          tmpfs  5.0M     0  5.0M   0% /run/lock
/dev/vda2      vfat   197M  5.3M  192M   3% /boot/efi
tmpfs          tmpfs   50M     0   50M   0% /usr/local/aegis/cgroup
tmpfs          tmpfs  743M  4.0K  743M   1% /run/user/0
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0 44.7M  1 loop /snap/snapd/15534
loop1    7:1    0 79.9M  1 loop /snap/lxd/22923
loop2    7:2    0 61.9M  1 loop /snap/core20/1405
vda    252:0    0   40G  0 disk 
├─vda1 252:1    0    1M  0 part 
├─vda2 252:2    0  200M  0 part /boot/efi
└─vda3 252:3    0 39.8G  0 part /` 

As you can see it has 3 partitions 
I'm creating a snapshot of it, from it a disk and attaching it like this 

`apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-sc
  csi:
    driver: diskplugin.csi.maxim.io
    volumeHandle: d-t4ncubv69a2hseucrtsj
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.diskplugin.csi.alibabacloud.com/zone
              operator: In
              values:
                - ap-southeast-1c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-sc
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-linux-volume
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.diskplugin.csi.alibabacloud.com/zone
                operator: In
                values:
                  - ap-southeast-1c
  containers:
    - image: ubuntu:latest
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      name: test-container
      volumeMounts:
        - mountPath: /test-alibaba
          name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: test-pvc
`

**Comment by maximrub** [comment]
@mowangdk what will be the effect of GlobalConfigVar.DiskPartitionEnable set to false on the GetDeviceByVolumeID function
I want based on the volume id to get the device

**Comment by mowangdk** [comment]
> @mowangdk is this a known limitation with the alibaba csi driver, because in the other clouds csi drivers azure, gcp, aws we don't have such issue

@maximrub  I checked the csi drivers of aws & gcp. All csi drivers do not support multiple partitions, they just allow to select one partition from multiple partitions to mount, but this is risky, if different partitions of one disk are mounted by different paths, csi unmounting will be a problem, so we disable all partitions of cloud disk uniformly. The env DiskPartitionEnable you mentioned only supports cloud disks with only one partition, cloud disks with three partitions like yours are not supported.

**Comment by maximrub** [comment]
@mowangdk thanks for your help
we were able to do it manually and mount them ourselves
it works for 2 partitions and in the mount command output we can see

```shell
/dev/vdb3 on /scanVolume type ext4 (rw,noatime)
/dev/vda1 on /config type ext4 (ro,relatime)
``` 

but we don't the third that is vfat type
for example on aws we do see it

```shell
/dev/nvme1n1p1 on /scanVolume type ext4 (rw,noatime)
/dev/nvme1n1p15 on /scanVolume/boot/efi type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
/dev/nvme0n1p1 on /config type xfs (ro,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
``` 

could it be because of the vfat type?

**Comment by mowangdk** [comment]
@maximrub Does the mount vfat command report any errors?

**Comment by maximrub** [comment]
@mowangdk the mount passes, but I found what is the problem
The value of CONFIG_FAT_DEFAULT_IOCHARSET is used as the default iocharset when a FAT filesystem is mounted
In my case the csi driver image is AliLinux3 and I'm loading a ubuntu image so iocharset is set to ascii instead iso8859-1

**Comment by maximrub** [comment]
@mowangdk if I'll pass "iocharset=utf8" in the mount options it should tackle the problem for all OS right?

**Comment by mowangdk** [comment]
> @mowangdk if I'll pass "iocharset=utf8" in the mount options it should tackle the problem for all OS right?

yeah, I think so

**Comment by maximrub** [comment]
@mowangdk little question, If I'll use ubutnu as the csi driver image instead alilinux3 will it work?
