### ISSUE TITLE
non root container mounts

### ISSUE THREAD

**Issue by sarnrich** [kubernetes-sigs/alibaba-cloud-csi-driver#801]
#### What happened:
When deploying containers with helm charts where non root user is used and a pv and pvc configures the CSI NAS, the actual mount is done with root:root rights on the filesystem.

SecurityContext of the deployment is not taken into account to mount the NAS with the according fsGroup.

#### What you expected to happen:

Beforehand we used flexvolume and the securityContext was taken into account to mount the volume according to fsGroup.

e.g.

```json
        "securityContext": {
          "fsGroup": 1001,
          "runAsNonRoot": true,
          "runAsUser": 1001
        },
```

should produce

drwxr-xr-x    1 root     1001         4096  ...mountedNASFilesystem

nevertheless with CSI we get

drwxr-xr-x    1 root     root          4096 ...mountedNASFilesystem

This stops the application logic from working as the non root user (1001) of the container cannot access mountedNASFilesystem.

#### How to reproduce it (as minimally and precisely as possible):

Try to deploy bitnami helm charts e.g. grafana with a existingClaim where PV and PVC are CSI configured pointing to a NAS.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.24.6-aliyun.1
- Cloud provider or hardware configuration: Alicloud Managed Kubernetes
- OS (e.g: `cat /etc/os-release`): 
containerd 1.6.20
AliyunLinux3
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by huww98** [comment]
Hi @sarnrich . We determine that this is not an issue with the CSI driver. As discussed in https://github.com/kubernetes/kubernetes/issues/66323, non-block storage (like NAS) is omitted from fsgroup changes intentionally by kubelet.

I would suggest changing the permission manually before creating the pods. Or if you still want to automate this, I suggest:
* use an init container to change the permission,
* or if you manually create the PV, set `accessModes` to `ReadWriteOnce` and `csi.fsType` to `nfs`. This would bypass the check in kubelet. Note this seems hacky and should only be used as a workaround.
