### ISSUE TITLE
mount nfs failed when change mount options

### ISSUE THREAD

**Issue by cataglyphis** [kubernetes-sigs/alibaba-cloud-csi-driver#810]
#### What happened:
1. origin nfs mount options: `vers=4,minorversion=0,hard,timeo=600,retrans=2,noresvport`
2. aliyun support suggest use `vers=3` to mount nfs in k8s, and we change the mount options to `vers=3,nolock,tcp,noresvport`
3. and changed mount options, then restart pod

time="2023-08-01T11:28:10+08:00" level=error msg="Nas, Mount Nfs error: Failed to run cmd: mount -t nfs -o vers=3,nolock,tcp,noresvport xxxxx.cn-shanghai.nas.aliyuncs.com:/data/nas-xxx /var/lib/kubelet/pods/7642daf1-8fc9-4eac-a4c3-4f91bf9911cb/volumes/kubernetes.io~csi/nas-xxx/mount, with out: mount.nfs: mount to NFS server 'xxxxx.cn-shanghai.nas.aliyuncs.com:/data/nas-xxx' failed: RPC Error: Success\n, with error: exit status 32"

E0801 11:28:10.485822  648456 utils.go:101] GRPC error: Nas, Mount Nfs error: %sFailed to run cmd: mount -t nfs -o vers=3,nolock,tcp,noresvport xxxxx.cn-shanghai.nas.aliyuncs.com:/data/nas-xxx /var/lib/kubelet/pods/7642daf1-8fc9-4eac-a4c3-4f91bf9911cb/volumes/kubernetes.io~csi/nas-aef172b8-e703-4d14-988d-48c8e99b0861/mount, with out: mount.nfs: mount to NFS server 'xxxxx.cn-shanghai.nas.aliyuncs.com:/data/nas-xxx' failed: RPC Error: Success
, with error: exit status 32

#### Environment:
- Kubernetes version (use `kubectl version`): 1.25.6，自建集群
- Cloud provider or hardware configuration:
- CSI: csi-plugin:v1.18.8.47-906bd535-aliyun
- CSI provisioner: csi-provisioner:v3.0.0-3f86569-aliyun
- OS (e.g: `cat /etc/os-release`): Rocky 9.2
- Kernel (e.g. `uname -a`): 5.14.0-284.18.1.el9_2.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tydra-wang** [comment]
@cataglyphis  Try to directly execute the mount command on the node and collect the logs.

**Comment by cataglyphis** [comment]
> 

run mount command manually, and everything works well, no error message

```
[root@ops-node110 ~]# mount -t nfs -o vers=3,nolock,tcp,noresvport 3254a495f2-xxx.cn-shanghai.nas.aliyuncs.com:/data/nas-aef172b8-e703-4d14-988d-xxx /mnt
[root@ops-node110 ~]# cd /mnt/
[root@ops-node110 mnt]# ls
```

**Comment by huww98** [comment]
@cataglyphis I cannot reproduce. I update the PV with `kubectl apply -f foo.yaml` then restart pods with `kubectl rollout restart deployment foo`. All works fine. Please provide more info about how you can reproduce this.
