### ISSUE TITLE
创建pod时，pvc创建出来的云盘无法挂载到node节点上

### ISSUE THREAD

**Issue by yiboyuanyuan** [kubernetes-sigs/alibaba-cloud-csi-driver#836]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/4b64ec11-320f-48f6-8309-7b5b9c0340b5)
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/93f8eb16-e2b4-45bb-a97d-687e5f8921c4)

**Comment by huww98** [comment]
Please see https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/docs/disk.md for how to deploy on self-built cluster.

If it still not working, please provide more details about your deployment, or we are not able to help you.

**Comment by yiboyuanyuan** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/5cf4e550-070e-4882-940a-cafc96ff35a0)
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/a1d44ca5-5406-4f22-a9b6-2bd27a2c84df)
第一个图是csi-provisioner
第二个图是创建pod，磁盘依旧挂载不上

**Comment by yiboyuanyuan** [comment]
k8s版本是1.27.4

**Comment by huww98** [comment]
请检查相关节点csi-plugin pod中两个容器的状态及日志，以及kubelet的日志。

**Comment by yiboyuanyuan** [comment]
csi-plugin容器
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/093fcf89-e82b-44b2-8260-b4c6545b8b22)
kubelet日志是正常的
麻烦问下csi是否支持k8s1.27.4版本

**Comment by yiboyuanyuan** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/9acff7ac-5609-44b9-a208-6980a463cf0a)

**Comment by yiboyuanyuan** [comment]
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/359d7681-dfc5-4f91-829f-12d0da1128a2)

**Comment by yiboyuanyuan** [comment]
Can't get nodeID from CSINode ali-fk-b-k8s-worker-02.uat.fosun.com: CSINode ali-fk-b-k8s-worker-02.uat.fosun.com does not contain driver diskplugin.csi.alibabacloud.com
csi-provisioner (external-disk-attacher)这个容器的日志 
所以才会挂载不上吧  这个是权限问题吗 麻烦看下谢谢 
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/95843199/a6633d53-fac3-4564-8b78-15bc1aa62575)

**Comment by huww98** [comment]
> 麻烦问下csi是否支持k8s1.27.4版本

我们并不支持在非ACK的集群上部署，因此未测试过。

> Can't get nodeID from CSINode ali-fk-b-k8s-worker-02.uat.fosun.com: CSINode ali-fk-b-k8s-worker-02.uat.fosun.com does not contain driver diskplugin.csi.alibabacloud.com

但仍未找到该错误的根本原因。CSINode应在csi-plugin注册时自动更新。可否提供csi-plugin pod中disk-driver-registrar的日志，以确定plugin是否注册成功。

**Comment by yiboyuanyuan** [comment]
I0824 08:18:46.843190 3906065 main.go:164] Version: unknown
I0824 08:18:46.843235 3906065 main.go:165] Running node-driver-registrar in mode=registration
I0824 08:18:46.843996 3906065 main.go:189] Attempting to open a gRPC connection with: "/var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock"
I0824 08:18:46.844036 3906065 connection.go:154] Connecting to unix:///var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock
I0824 08:18:50.124447 3906065 main.go:196] Calling CSI driver to discover driver name
I0824 08:18:50.124481 3906065 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginInfo
I0824 08:18:50.124489 3906065 connection.go:184] GRPC request: {}
I0824 08:18:50.129281 3906065 connection.go:186] GRPC response: {"name":"diskplugin.csi.alibabacloud.com","vendor_version":"1.0.0"}
I0824 08:18:50.129377 3906065 connection.go:187] GRPC error: <nil>
I0824 08:18:50.129389 3906065 main.go:206] CSI driver name: "diskplugin.csi.alibabacloud.com"
I0824 08:18:50.129426 3906065 node_register.go:52] Starting Registration Server at: /registration/diskplugin.csi.alibabacloud.com-reg.sock
I0824 08:18:50.129717 3906065 node_register.go:61] Registration Server started at: /registration/diskplugin.csi.alibabacloud.com-reg.sock
I0824 08:18:50.129796 3906065 node_register.go:91] Skipping healthz server because HTTP endpoint is set to: ""

**Comment by huww98** [comment]
从日志看，尚未触发csi-plugin的注册动作。你的kubelet根目录是否是`/var/lib/kubelet`？若否，请尝试对应修改yaml中`kubelet-dir`这个volume的路径。

**Comment by yiboyuanyuan** [comment]
可以了 谢谢
