### ISSUE TITLE
Can I use local-lvm in self-built k8s cluster(no ACK cluster, no aliyun environment)?

### ISSUE THREAD

**Issue by tagGeeY** [kubernetes-sigs/alibaba-cloud-csi-driver#847]
I follow steps in this document: [如何使用LVM数据卷_容器服务 Kubernetes 版 ACK-阿里云帮助中心](https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/use-lvs?spm=a2c4g.11186623.0.0.3ebf654c5dsAAy#section-rus-sw8-7wn). 
csi-localprovisioner pod CrashLoopBackOff:
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/35259969/53fac4cf-b446-4fb9-bcdd-5f3679740dc8)

csi-localplugin pod start failed:
![image](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/assets/35259969/eb789138-6838-4a13-8a75-95f43c1ae044)

**Comment by huww98** [comment]
Theoretically yes. But no support from us, and we have not tested for this use case. You may need some hack to make it work.
