### ISSUE TITLE
VolumeSnapshotClass tags

### ISSUE THREAD

**Issue by shusaan** [kubernetes-sigs/alibaba-cloud-csi-driver#900]
Here is the VolumeSnapshotClass, 

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: alibaba-disk-snapshot
driver: diskplugin.csi.alibabacloud.com
deletionPolicy: Delete
```

how can we add Tags for VolumeSnapshotClass, is that supported ?

**Comment by huww98** [comment]
Do you mean add custom tags to the created snapshot, so that you can see them in ECS console? If so, not supported now.

**Comment by shusaan** [comment]
yes, custom tag like env=test.
I have checked this one https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/438
what about this one.
