### ISSUE TITLE
snapshot creation failing

### ISSUE THREAD

**Issue by sateesh9in** [kubernetes-sigs/alibaba-cloud-csi-driver#970]
#### What happened:
snapshot creation faileing.

#### What you expected to happen:
snapshot should create successfully.

#### How to reproduce it (as minimally and precisely as possible):
deploy csi-plugin as per below kb.
https://www.alibabacloud.com/help/en/nas/user-guide/mount-a-nas-file-system-on-a-self-managed-kubernetes-cluster

#### Environment:
- CSI driver version (image tag of csi-plugin container):
v1.24.5-39a3970-aliyun

- Deployment method (where you got the YAML files, what modifications you made, etc.):
YAML

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12+rke2r1", GitCommit:"ba490f01df1945d0567348b271c79a2aece7f623", GitTreeState:"clean", BuildDate:"2023-07-19T20:59:13Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12+rke2r1", GitCommit:"ba490f01df1945d0567348b271c79a2aece7f623", GitTreeState:"clean", BuildDate:"2023-07-19T20:59:13Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration (e.g. Alibaba Cloud ECS instance type):
Self managed RKE2 k8s cluster  using ABC ECS instances

- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- Kernel (e.g. `uname -a`):
Linux central-1a-ac 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Logs:

k get volumesnapshot -A
NAMESPACE   NAME                            READYTOUSE   SOURCEPVC       SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                SNAPSHOTCONTENT                                    CREATIONTIME   AGE
default     volume-snapshot-abc-disk-ssd1   false        abc-disk-ssd1                                         alibabacloud-disk-snapshot   snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa                  36m

37m         Warning   SnapshotCreateError      volumesnapshot/volume-snapshot-abc-disk-ssd1   rpc error: code = Internal desc = failed create snapshot: SDK.ServerError...
37m         Warning   SnapshotCreateError      volumesnapshot/volume-snapshot-abc-disk-ssd1   rpc error: code = Internal desc = failed create snapshot: SDK.ServerError...
36m         Warning   SnapshotCreateError      volumesnapshot/volume-snapshot-abc-disk-ssd1   rpc error: code = Internal desc = failed create snapshot: SDK.ServerError...
36m         Warning   SnapshotCreateError      volumesnapshot/volume-snapshot-abc-disk-ssd1   rpc error: code = Internal desc = failed create snapshot: SDK.ServerError...

I0205 05:00:53.320030 1060552 util.go:297] storeObjectUpdate updating content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" with version 128469504
I0205 05:00:53.320046 1060552 snapshot_controller.go:592] setAnnVolumeSnapshotBeingCreated: volume snapshot content &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa GenerateName: Namespace: SelfLink: UID:398ae24f-cfb1-43bc-bac6-72784295e9e0 ResourceVersion:128469504 Generation:1 CreationTimestamp:2024-02-05 04:46:54 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] OwnerReferences:[] Finalizers:[snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection] ClusterName: ManagedFields:[{Manager:snapshot-controller Operation:Update APIVersion:snapshot.storage.k8s.io/v1 Time:2024-02-05 04:46:54 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:finalizers":{".":{},"v:\"snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection\"":{}}},"f:spec":{".":{},"f:deletionPolicy":{},"f:driver":{},"f:source":{".":{},"f:volumeHandle":{}},"f:volumeSnapshotClassName":{},"f:volumeSnapshotRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}}}} {Manager:csi-snapshotter Operation:Update APIVersion:snapshot.storage.k8s.io/v1 Time:2024-02-05 05:00:47 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:annotations":{".":{},"f:snapshot.storage.kubernetes.io/volumesnapshot-being-created":{}}}}}]} Spec:{VolumeSnapshotRef:{Kind:VolumeSnapshot Namespace:default Name:volume-snapshot-abc-disk-ssd1 UID:f9fd1225-55ca-443c-a670-bab858d919fa APIVersion:snapshot.storage.k8s.io/v1 ResourceVersion:128458295 FieldPath:} DeletionPolicy:Delete Driver:diskplugin.csi.alibabacloud.com VolumeSnapshotClassName:0xc0009a40a0 Source:{VolumeHandle:0xc0009a4090 SnapshotHandle:<nil>}} Status:<nil>}
I0205 05:00:53.320112 1060552 snapshotter.go:56] CSI CreateSnapshot: snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.320120 1060552 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0205 05:00:53.320124 1060552 connection.go:183] GRPC request: {}
I0205 05:00:53.320400 1060552 connection.go:185] GRPC response: {"name":"diskplugin.csi.alibabacloud.com","vendor_version":"1.0.0"}
I0205 05:00:53.320423 1060552 connection.go:186] GRPC error: <nil>
I0205 05:00:53.320428 1060552 connection.go:182] GRPC call: /csi.v1.Controller/CreateSnapshot
I0205 05:00:53.320431 1060552 connection.go:183] GRPC request: {"name":"snapshot-f9fd1225-55ca-443c-a670-bab858d919fa","parameters":{"csi.storage.k8s.io/volumesnapshot/name":"volume-snapshot-abc-disk-ssd1","csi.storage.k8s.io/volumesnapshot/namespace":"default","csi.storage.k8s.io/volumesnapshotcontent/name":"snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa"},"source_volume_id":"d-l4v0xjvzgvrphmzskea8"}
I0205 05:00:53.320461 1060552 snapshot_controller_base.go:143] enqueued "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" for sync
I0205 05:00:53.320715 1060552 connection.go:185] GRPC response: {}
I0205 05:00:53.320736 1060552 connection.go:186] GRPC error: rpc error: code = Unknown desc = CreateSnapshot: snapshot create request limit snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.320750 1060552 snapshot_controller.go:301] createSnapshotWrapper: CreateSnapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa returned error: rpc error: code = Unknown desc = CreateSnapshot: snapshot create request limit snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.320760 1060552 snapshot_controller.go:141] updateContentStatusWithEvent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.513139 1060552 request.go:591] Throttling request took 192.309426ms, request: PUT:https://10.96.0.1:443/apis/snapshot.storage.k8s.io/v1/volumesnapshotcontents/snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa/status
I0205 05:00:53.520319 1060552 snapshot_controller.go:165] updating VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa": the object has been modified; please apply your changes to the latest version and try again
E0205 05:00:53.520329 1060552 snapshot_controller.go:105] createSnapshot for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
E0205 05:00:53.520337 1060552 snapshot_controller_base.go:264] could not sync content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa": failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:53.520352 1060552 snapshot_controller_base.go:166] Failed to sync content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa", will retry again: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:53.520363 1060552 snapshot_controller_base.go:177] syncContentByKey[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.520376 1060552 util.go:297] storeObjectUpdate updating content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" with version 128469504
I0205 05:00:53.520386 1060552 snapshot_controller.go:56] synchronizing VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.520391 1060552 snapshot_controller.go:540] Check if VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa] should be deleted.
I0205 05:00:53.520396 1060552 snapshot_controller.go:75] syncContent: Call CreateSnapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.520401 1060552 snapshot_controller.go:101] createSnapshot for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]: started
I0205 05:00:53.520406 1060552 snapshot_controller.go:267] createSnapshotWrapper: Creating snapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa through the plugin ...
I0205 05:00:53.520411 1060552 snapshot_controller.go:180] getCSISnapshotInput for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.520416 1060552 snapshot_controller.go:448] getSnapshotClass: VolumeSnapshotClassName [alibabacloud-disk-snapshot]
I0205 05:00:53.520431 1060552 snapshotter.go:56] CSI CreateSnapshot: snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.520442 1060552 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0205 05:00:53.520427 1060552 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:53.520448 1060552 connection.go:183] GRPC request: {}
I0205 05:00:53.520727 1060552 connection.go:185] GRPC response: {"name":"diskplugin.csi.alibabacloud.com","vendor_version":"1.0.0"}
I0205 05:00:53.520755 1060552 connection.go:186] GRPC error: <nil>
I0205 05:00:53.520761 1060552 connection.go:182] GRPC call: /csi.v1.Controller/CreateSnapshot
I0205 05:00:53.520766 1060552 connection.go:183] GRPC request: {"name":"snapshot-f9fd1225-55ca-443c-a670-bab858d919fa","parameters":{"csi.storage.k8s.io/volumesnapshot/name":"volume-snapshot-abc-disk-ssd1","csi.storage.k8s.io/volumesnapshot/namespace":"default","csi.storage.k8s.io/volumesnapshotcontent/name":"snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa"},"source_volume_id":"d-l4v0xjvzgvrphmzskea8"}
I0205 05:00:53.521102 1060552 connection.go:185] GRPC response: {}
I0205 05:00:53.521127 1060552 connection.go:186] GRPC error: rpc error: code = Unknown desc = CreateSnapshot: snapshot create request limit snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.521143 1060552 snapshot_controller.go:301] createSnapshotWrapper: CreateSnapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa returned error: rpc error: code = Unknown desc = CreateSnapshot: snapshot create request limit snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.713451 1060552 request.go:591] Throttling request took 192.234627ms, request: PUT:https://10.96.0.1:443/apis/snapshot.storage.k8s.io/v1/volumesnapshotcontents/snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.722735 1060552 snapshot_controller_base.go:143] enqueued "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" for sync
I0205 05:00:53.722761 1060552 snapshot_controller.go:614] Removed VolumeSnapshotBeingCreated annotation from volume snapshot content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.722773 1060552 util.go:297] storeObjectUpdate updating content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" with version 128469524
I0205 05:00:53.722783 1060552 snapshot_controller.go:141] updateContentStatusWithEvent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.913120 1060552 request.go:591] Throttling request took 190.253344ms, request: PUT:https://10.96.0.1:443/apis/snapshot.storage.k8s.io/v1/volumesnapshotcontents/snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa/status
I0205 05:00:53.916686 1060552 snapshot_controller.go:165] updating VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa": the object has been modified; please apply your changes to the latest version and try again
E0205 05:00:53.916697 1060552 snapshot_controller.go:105] createSnapshot for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
E0205 05:00:53.916705 1060552 snapshot_controller_base.go:264] could not sync content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa": failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:53.916718 1060552 snapshot_controller_base.go:166] Failed to sync content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa", will retry again: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:53.916726 1060552 snapshot_controller_base.go:177] syncContentByKey[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.916738 1060552 util.go:297] storeObjectUpdate updating content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" with version 128469524
I0205 05:00:53.916747 1060552 snapshot_controller.go:56] synchronizing VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.916752 1060552 snapshot_controller.go:540] Check if VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa] should be deleted.
I0205 05:00:53.916758 1060552 snapshot_controller.go:75] syncContent: Call CreateSnapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:53.916762 1060552 snapshot_controller.go:101] createSnapshot for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]: started
I0205 05:00:53.916768 1060552 snapshot_controller.go:267] createSnapshotWrapper: Creating snapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa through the plugin ...
I0205 05:00:53.916773 1060552 snapshot_controller.go:180] getCSISnapshotInput for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:53.916778 1060552 snapshot_controller.go:448] getSnapshotClass: VolumeSnapshotClassName [alibabacloud-disk-snapshot]
I0205 05:00:53.916768 1060552 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:53.916784 1060552 snapshot_controller.go:577] setAnnVolumeSnapshotBeingCreated: set annotation [snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] on content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa].
I0205 05:00:54.112999 1060552 request.go:591] Throttling request took 196.110346ms, request: PUT:https://10.96.0.1:443/apis/snapshot.storage.k8s.io/v1/volumesnapshotcontents/snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:54.120106 1060552 snapshot_controller_base.go:143] enqueued "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" for sync
I0205 05:00:54.120729 1060552 util.go:297] storeObjectUpdate updating content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" with version 128469526
I0205 05:00:54.120744 1060552 snapshot_controller.go:592] setAnnVolumeSnapshotBeingCreated: volume snapshot content &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa GenerateName: Namespace: SelfLink: UID:398ae24f-cfb1-43bc-bac6-72784295e9e0 ResourceVersion:128469526 Generation:1 CreationTimestamp:2024-02-05 04:46:54 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] OwnerReferences:[] Finalizers:[snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection] ClusterName: ManagedFields:[{Manager:snapshot-controller Operation:Update APIVersion:snapshot.storage.k8s.io/v1 Time:2024-02-05 04:46:54 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:finalizers":{".":{},"v:\"snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection\"":{}}},"f:spec":{".":{},"f:deletionPolicy":{},"f:driver":{},"f:source":{".":{},"f:volumeHandle":{}},"f:volumeSnapshotClassName":{},"f:volumeSnapshotRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}}}} {Manager:csi-snapshotter Operation:Update APIVersion:snapshot.storage.k8s.io/v1 Time:2024-02-05 05:00:48 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:annotations":{".":{},"f:snapshot.storage.kubernetes.io/volumesnapshot-being-created":{}}}}}]} Spec:{VolumeSnapshotRef:{Kind:VolumeSnapshot Namespace:default Name:volume-snapshot-abc-disk-ssd1 UID:f9fd1225-55ca-443c-a670-bab858d919fa APIVersion:snapshot.storage.k8s.io/v1 ResourceVersion:128458295 FieldPath:} DeletionPolicy:Delete Driver:diskplugin.csi.alibabacloud.com VolumeSnapshotClassName:0xc000890b00 Source:{VolumeHandle:0xc000890af0 SnapshotHandle:<nil>}} Status:<nil>}
I0205 05:00:54.120814 1060552 snapshotter.go:56] CSI CreateSnapshot: snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:54.120824 1060552 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0205 05:00:54.120830 1060552 connection.go:183] GRPC request: {}
I0205 05:00:54.121123 1060552 connection.go:185] GRPC response: {"name":"diskplugin.csi.alibabacloud.com","vendor_version":"1.0.0"}
I0205 05:00:54.121159 1060552 connection.go:186] GRPC error: <nil>
I0205 05:00:54.121165 1060552 connection.go:182] GRPC call: /csi.v1.Controller/CreateSnapshot
I0205 05:00:54.121169 1060552 connection.go:183] GRPC request: {"name":"snapshot-f9fd1225-55ca-443c-a670-bab858d919fa","parameters":{"csi.storage.k8s.io/volumesnapshot/name":"volume-snapshot-abc-disk-ssd1","csi.storage.k8s.io/volumesnapshot/namespace":"default","csi.storage.k8s.io/volumesnapshotcontent/name":"snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa"},"source_volume_id":"d-l4v0xjvzgvrphmzskea8"}
I0205 05:00:54.121437 1060552 connection.go:185] GRPC response: {}
I0205 05:00:54.121463 1060552 connection.go:186] GRPC error: rpc error: code = Unknown desc = CreateSnapshot: snapshot create request limit snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:54.121474 1060552 snapshot_controller.go:301] createSnapshotWrapper: CreateSnapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa returned error: rpc error: code = Unknown desc = CreateSnapshot: snapshot create request limit snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:54.121488 1060552 snapshot_controller.go:141] updateContentStatusWithEvent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:54.312787 1060552 request.go:591] Throttling request took 191.22918ms, request: PUT:https://10.96.0.1:443/apis/snapshot.storage.k8s.io/v1/volumesnapshotcontents/snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa/status
I0205 05:00:54.318111 1060552 snapshot_controller.go:165] updating VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa": the object has been modified; please apply your changes to the latest version and try again
E0205 05:00:54.318124 1060552 snapshot_controller.go:105] createSnapshot for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
E0205 05:00:54.318133 1060552 snapshot_controller_base.go:264] could not sync content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa": failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:54.318146 1060552 snapshot_controller_base.go:166] Failed to sync content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa", will retry again: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:54.318154 1060552 snapshot_controller_base.go:177] syncContentByKey[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:54.318166 1060552 util.go:297] storeObjectUpdate updating content "snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa" with version 128469526
I0205 05:00:54.318175 1060552 snapshot_controller.go:56] synchronizing VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:54.318180 1060552 snapshot_controller.go:540] Check if VolumeSnapshotContent[snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa] should be deleted.
I0205 05:00:54.318185 1060552 snapshot_controller.go:75] syncContent: Call CreateSnapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:54.318189 1060552 snapshot_controller.go:101] createSnapshot for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]: started
I0205 05:00:54.318199 1060552 snapshot_controller.go:267] createSnapshotWrapper: Creating snapshot for content snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa through the plugin ...
I0205 05:00:54.318204 1060552 snapshot_controller.go:180] getCSISnapshotInput for content [snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa]
I0205 05:00:54.318208 1060552 snapshot_controller.go:448] getSnapshotClass: VolumeSnapshotClassName [alibabacloud-disk-snapshot]
I0205 05:00:54.318200 1060552 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)
I0205 05:00:54.318220 1060552 snapshotter.go:56] CSI CreateSnapshot: snapshot-f9fd1225-55ca-443c-a670-bab858d919fa
I0205 05:00:54.318229 1060552 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0205 05:00:54.318235 1060552 connection.go:183] GRPC request: {}
I0205 05:00:54.318516 1060552 connection.go:185] GRPC response: {"name":"diskplugin.csi.alibabacloud.com","vendor_version":"1.0.0"}
I0205 05:00:54.318544 1060552 connection.go:186] GRPC error: <nil>
I0205 05:00:54.318549 1060552 connection.go:182] GRPC call: /csi.v1.Controller/CreateSnapshot
I0205 05:00:54.318553 1060552 connection.go:183] GRPC request: {"name":"snapshot-f9fd1225-55ca-443c-a670-bab858d919fa","parameters":{"csi.storage.k8s.io/volumesnapshot/name":"volume-snapshot-abc-disk-ssd1","csi.storage.k8s.io/volumesnapshot/namespace":"default","csi.storage.k8s.io/volumesnapshotcontent/name":"snapcontent-f9fd1225-55ca-443c-a670-bab858d919fa"},"source_volume_id":"d-l4v0xjvzgvrphmzskea8"}

**Comment by mowangdk** [comment]
@sateesh9in  Is there any events for the VolumeSnapshot resource? it seems like an openapi error by ```37m Warning SnapshotCreateError volumesnapshot/volume-snapshot-abc-disk-ssd1 rpc error: code = Internal desc = failed create snapshot: SDK.ServerError...```

**Comment by sateesh9in** [comment]
hi mowangdk,

I am getting below event 

2m38s       Warning   SnapshotCreateError      volumesnapshot/volume-snapshot-abc-disk-ssd1   (combined from similar events): rpc error: code = Internal desc = failed create snapshot: SDK.ServerError...

     MESSAGE
3m46s       Warning   SnapshotCreationFailed   volumesnapshotcontent                          Failed to create snapshot: failed to take snapshot of the volume, d-l4v0xjvzgvrphmzskea8: %!q(<nil>)



Thanks 
Sateesh

**Comment by huww98** [comment]
> code = Internal desc = failed create snapshot: SDK.ServerError...

This message seems to be truncated. I'm not sure why. You may search for the log for `SDK.ServerError`, and see if you can get the complete message.
