### ISSUE TITLE
Is lvm combined to local？

### ISSUE THREAD

**Issue by hzliangbin** [kubernetes-sigs/alibaba-cloud-csi-driver#988]
I have noticed that some dead codes were deleted in latest commits about lvm. Just want to know lvm combined to local? or no support any more.

Thanks for calarification.

**Comment by hzliangbin** [comment]
@huww98 gentle ping

**Comment by huww98** [comment]
local driver is also removed from this repo now. New users should use https://github.com/alibaba/open-local . We still provide and maintain a close sourced version of local driver for ACK cluster.
/close
